data/types/calculator/calculator.go
data/types/calculator/calculator_test.go
data/types/cgm/cgm_settings.go
data/types/cgm/cgm_settings_test.go

@darinkrauss this should be all the cleanup needed

update tests to reflect what is needed for parsing animas data

---

data/types/calculator/calculator.go
data/types/calculator/calculator_test.go

@jh-bate More data changes to allow Animas pump to upload. I commented everything with `TODO_DATA` so you can find it again to review and make changes.

Make calculator blood glucose target high and low optional for Animas

---

data/types/base.go
data/types/device/alarm.go
data/types/device/alarm_test.go
data/types/device/base.go
data/types/device/calibration_test.go
data/types/device/prime.go
data/types/device/prime_test.go
data/types/device/status.go
data/types/device/status_test.go
data/types/device/time_change.go
data/types/device/time_change_test.go
data/types/ketone/blood_ketone_test.go
data/types/upload/upload.go
data/types/upload/upload_test.go

@darinkrauss validation and tests updated based on docs.

Device event validation

---

data/types/basal/base.go

Try int when parsing float

---

data/types/basal/scheduled.go
data/types/basal/scheduled_test.go

@jh-bate @darinkrauss I've added a test for zero rate basals that currently fails the validation.

Zero rate basals

---

pvn/data/context/standard.go
pvn/data/context/standard_test.go
service/error.go

@jh-bate Just going to merge to master once this passes CI tests.

Fix issue with error source pointer in PVN context

---

data/deduplicator/truncate/truncate.go
log/log.go
store/mongo/mongo.go

@jh-bate Attempt to fix the slow performance on `stg`. Three separate, very focused commits.

General performance/logging improvements

---

data/context/standard_test.go
data/normalizer/standard_test.go
data/parser/standard_array_test.go
data/parser/standard_object_test.go
data/validator/standard_boolean_test.go
data/validator/standard_float_as_blood_glucose_value_test.go
data/validator/standard_float_test.go
data/validator/standard_integer_test.go
data/validator/standard_interface_array_test.go
data/validator/standard_interface_test.go
data/validator/standard_object_array_test.go
data/validator/standard_object_test.go
data/validator/standard_string_array_test.go
data/validator/standard_string_as_blood_glucose_units_test.go
data/validator/standard_string_as_time_test.go
data/validator/standard_string_test.go
data/validator/standard_test.go

@jh-bate I did this last week, but apparently forgot to push it up and have you do a PR. It is only changes to tests.

More specific error tests

---

data/types/base/bolus/combination/combination.go
data/types/base/bolus/combination/combination_test.go
data/types/base/bolus/extended/extended.go
data/types/base/bolus/extended/extended_test.go
data/types/base/bolus/normal/normal.go
data/types/base/bolus/normal/normal_test.go

@jh-bate @gniezen I think I have all of the boluses using correct validations and tests.

Fix validation for normal, extended, and combination boluses; tests

---

data/types/base/upload/upload.go

@jh-bate Remove dataState and deduplicator from output; remove commented out code.

Upload DataState and Deduplicator are private

---

README.md

(What it says on the tin. @darinkrauss merge if you think useful.)

add a comment re: reuse of exports

---

_config/data_store.local.json

Please see synchronize_databases/README.md in the tools repo for more information.
@jh-bate

Synchronize database and collection names between localhost and deployed

---

tools/migrate_gid_to_uid/migrate_gid_to_uid.go

@jh-bate What it says on the tin

Additional sanity checks and logging for migrate_gid_to_uid

---

dataservices/client/client.go
dataservices/client/client_suite_test.go
dataservices/client/config.go
dataservices/client/config_test.go
dataservices/client/standard.go
dataservices/client/standard_test.go
metricservices/client/standard_test.go

@jh-bate Dataservices client so that the delete user API call can into the dataservices and delete all of the data for the user

Dataservices client

---

app/crypto.go
app/crypto_test.go

AES-256 encryption using passphrase for permissions group id generation

---

message/store/mongo/mongo.go
message/store/mongo/mongo_test.go
message/store/store.go

Delete messages associated with deleted user

---

notification/store/mongo/mongo.go
notification/store/mongo/mongo_test.go
notification/store/store.go

Delete notifications associated with deleted user

---

_config/userservices/permission_store.local.json
permission/store/mongo/config.go
permission/store/mongo/config_test.go
permission/store/mongo/mongo.go
permission/store/mongo/mongo_test.go
permission/store/store.go
userservices/service/service/standard.go

Delete permissions associated with deleted user

---

profile/profile.go
profile/store/mongo/mongo.go
profile/store/mongo/mongo_test.go
profile/store/store.go

Delete profile associated with deleted user

---

session/store/mongo/mongo.go
session/store/mongo/mongo_test.go
session/store/store.go

Delete sessions associated with deleted user

---

task/store/mongo/mongo_test.go

Update task tests to have exact expectations after delete

---

_config/userservices/user_store.local.json
user/store/mongo/config.go
user/store/mongo/config_test.go
user/store/mongo/mongo.go
user/store/mongo/mongo_test.go
user/store/store.go
user/user.go
userservices/service/service/standard.go

Various user store functions associated with deleted user

---

userservices/service/api/v1/users_delete.go
userservices/service/api/v1/users_delete_test.go
userservices/service/api/v1/v1.go
userservices/service/api/v1/v1_suite_test.go
userservices/service/api/v1/v1_test.go
userservices/service/context/standard.go

@jh-bate Final PR. Adds the actual endpoint and ties all of the previous code/PRs together.

Add delete user endpoint and tests

---

Makefile
data/store/mongo/mongo_test.go
message/store/mongo/mongo.go
service/middleware/trace.go
store/mongo/mongo.go
store/mongo/mongo_test.go
store/store.go
tools/tapi/api/api.go
tools/tapi/api/request.go
tools/tapi/api/user.go
tools/tapi/cmd/cmd.go
tools/tapi/cmd/user.go
user/store/mongo/mongo.go
user/store/mongo/mongo_test.go

@jh-bate Primarily updating the tapi tool to add delete user functionality. Also moved over add/remove role (for clinics). Minor refactoring to improve trace request carry-through for outgoing requests.

Add new user-related features to tapi tool; minor refactoring

---

.govetignore
.travis.yml
Godeps/Godeps.json
Makefile
config/config.go
permission/store/mongo/config.go
user/store/mongo/config.go
vendor/github.com/golang/protobuf/proto/encode.go
vendor/github.com/onsi/ginkgo/CHANGELOG.md
vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
vendor/github.com/satori/go.uuid/.travis.yml
vendor/github.com/tidepool-org/configor/README.md
vendor/github.com/tidepool-org/configor/configor.go
vendor/github.com/urfave/cli/errors.go
vendor/golang.org/x/crypto/ssh/terminal/util_solaris.go
vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
vendor/gopkg.in/yaml.v2/decode.go

@jh-bate This primarily uses the updated version of configor, but I took the opportunity to update to the latest dependencies and latest version of Go. Since the testing for this needs to be fairly extensive (deleting a user needs to ensure nothing untoward happens throughout the app if another user tries to operate on data belonging to the deleted user), I figured it would be a good time to do this update.

Update go version; update dependencies; use Tidepool fork of configor

---

data/types/base/basal/basal.go
data/types/base/basal/basal_test.go
data/types/base/basal/scheduled/scheduled.go
data/types/base/basal/scheduled/scheduled_test.go
data/types/base/basal/suppressed.go
data/types/base/basal/suppressed_test.go
data/types/base/basal/suspend/suspend.go
data/types/base/basal/suspend/suspend_test.go
data/types/base/basal/temporary/temporary.go
data/types/base/basal/temporary/temporary_test.go
data/types/base/base.go
data/types/base/bolus/calculator/calculator.go
data/types/base/bolus/calculator/calculator_test.go
data/types/base/device/reservoirchange/reservoirchange.go
data/types/base/device/reservoirchange/reservoirchange_test.go
data/types/base/pump/carbohydrate_ratio.go
data/types/base/pump/settings_test.go

@jh-bate Last changes needed to latest uploader work. Basal suppressed added refactored and completed. Add correct status sub-object to deviceEvent/reservoirchange. Other minor updates.

Parse full basal, reservoirchange, minor type changes

---

.env
tools/tapi/README.md
tools/tapi/api/request.go

@jh-bate I will have to update the config as well, but wanted to make it consistent.

Update tools to use correct environment variable for server secret

---

app/string.go
app/string_test.go
data/deduplicator/truncate.go
data/deduplicator/truncate_test.go
data/types/base/basal/suppressed.go
user/user.go

Truncate deduplicator only handles Animas devices

---

data/store/mongo/mongo.go

@jh-bate Really minor rename of `selector` to `query` local variable when invoking `Find` (more accurate).

Minor local variable name cleanup for accuracy

---

data/types/base/blood/glucose/continuous/continuous.go
data/types/base/blood/glucose/selfmonitored/selfmonitored.go
data/types/base/blood/ketone/ketone.go

@jh-bate Simple fix of type names to match data type reorganization.

Type name fixes

---

data/types/base/basal/basal.go
data/types/base/basal/scheduled/scheduled.go
data/types/base/basal/suspend/suspend.go
data/types/base/basal/temporary/temporary.go
data/types/base/blood/glucose/selfmonitored/selfmonitored.go
data/types/base/bolus/bolus.go
data/types/base/bolus/calculator/calculator.go
data/types/base/bolus/combination/combination.go
data/types/base/bolus/extended/extended.go
data/types/base/bolus/normal/normal.go
data/types/base/device/alarm/alarm.go
data/types/base/device/calibration/calibration.go
data/types/base/device/device.go
data/types/base/device/prime/prime.go
data/types/base/device/reservoirchange/reservoirchange.go
data/types/base/device/status/status.go
data/types/base/device/timechange/timechange.go
data/types/base/settings/pump/pump.go
data/types/base/upload/upload.go

@jh-bate Simple removal of unnecessary embedded struct references.

Remove unnecessary embedded struct references

---

data/types/base/basal/basal.go
data/types/base/basal/basal_test.go
data/types/base/basal/scheduled/scheduled.go
data/types/base/basal/scheduled/scheduled_test.go
data/types/base/basal/suspend/suspend.go
data/types/base/basal/suspend/suspend_test.go
data/types/base/basal/temporary/temporary.go
data/types/base/basal/temporary/temporary_test.go
data/types/base/base.go
data/types/base/blood/glucose/continuous/continuous.go
data/types/base/blood/glucose/continuous/continuous_test.go
data/types/base/blood/glucose/selfmonitored/selfmonitored.go
data/types/base/blood/glucose/selfmonitored/selfmonitored_test.go
data/types/base/blood/ketone/ketone.go
data/types/base/blood/ketone/ketone_test.go
data/types/base/bolus/bolus.go
data/types/base/bolus/combination/combination.go
data/types/base/bolus/extended/extended.go
data/types/base/bolus/normal/normal.go
data/types/base/calculator/calculator.go
data/types/base/device/alarm/alarm.go
data/types/base/device/calibration/calibration.go
data/types/base/device/device.go
data/types/base/device/prime/prime.go
data/types/base/device/reservoirchange/reservoirchange.go
data/types/base/device/status/status.go
data/types/base/device/timechange/timechange.go
data/types/base/settings/pump/pump.go
data/types/base/upload/upload.go

@jh-bate Validate type and subType/deliveryTypes, as appropriate. Test validation of base.ID for various data types.

Validate type and subType/deliveryType are specified and correct

---

data/store/mongo/mongo_test.go

@jh-bate Explicitly add test data for *another* user to ensure that tests only affect the target user.

Add data for other user in mongo tests

---

data/deduplicator/truncate.go
data/deduplicator/truncate_test.go

@jh-bate Minor changes in preparation for using this test file as a template for the hash deduplicator tests.

Minor refinements to truncate deduplicator tests

---

data/deduplicator/hash.go
data/deduplicator/hash_test.go
data/deduplicator/truncate_test.go
data/store/mongo/mongo.go
data/store/mongo/mongo_test.go
data/store/store.go
data/store/test/session.go
dataservices/service/api/v1/datasets_data_create.go
dataservices/service/api/v1/users_datasets_get_test.go
dataservices/service/service/standard.go

@jh-bate Hash deduplicator. Data store changes. Minor updates.

Hash deduplicator

---

tools/tapi/README.md

Because I had some trouble using `tapi` locally.
Ping @darinkrauss

add some additional instructions for localhost use on tapi README

---

tools/migrate_pmid_to_uid/migrate_pmid_to_uid.go

@jh-bate Added a bit of debugging information

Update migrate_pmid_to_uid for additional debugging information

---

tools/migrate_pmid_to_uid/migrate_pmid_to_uid.go

@jh-bate Fix a chicken-and-egg problem @krystophv ran into.

Optionally add unique index after migration; update log messages

---

app/crypto.go
app/crypto_test.go
permission/permission.go
permission/permission_suite_test.go
permission/permission_test.go
permission/store/mongo/mongo.go
permission/store/mongo/mongo_test.go
tools/permission_gid/permission_gid.go

@jh-bate This has been hanging out for a while. I needed to write this tool to get data that Brandon wanted.

Tool to encode/decode Gatekeeper ids

---

Dockerfile.dataservices
Dockerfile.userservices
Makefile

Add Dockerfile per service that needs to run.
Update `Makefile` to support Alpine Linux's lack of `xargs -L`

Add support for creation of Docker containers for platform services

---

.travis.yml
crypto/crypto.go
crypto/crypto_suite_test.go
crypto/crypto_test.go
permission/permission.go
permission/store/mongo/mongo_test.go

Break out crypto functions into separate package

---

data/deduplicator/hash_deactivate_old.go
data/deduplicator/hash_deactivate_old_test.go
data/store/mongo/mongo.go
data/store/mongo/mongo_test.go
data/store/store.go
data/store/test/session.go

Fix hash deactivate old deduplicator for uploads with invalid timezone

---

data/types/upload/upload.go
data/types/upload/upload_test.go

@jh-bate Fix the bug discussion in the company meeting today.

Allow valid SemVer version strings in upload type data record

---

data/deduplicator/hash_deactivate_old.go
dataservices/service/context/standard.go

@jh-bate @pazaan More 6-series devices

Support additional Medtronic devices

---

data/types/device/prime/prime.go
data/types/device/prime/prime_test.go

@jh-bate Update from 3 to 10 units per cannula fill.

Update device/prime volume to allow maximum of 10 units for cannula

---

CHANGELOG.md
application/application.go
application/application_test.go
data/service/service/standard.go
service/service.go
service/service_test.go
services/dataservices/dataservices.go
services/userservices/userservices.go
tool/mongo/tool.go
tool/mongo/tool_test.go
tool/tool.go
tool/tool_test.go
tools/migrate_data_deduplicator_descriptor/migrate_data_deduplicator_descriptor.go
tools/migrate_gid_to_uid/migrate_gid_to_uid.go
tools/migrate_pmid_to_uid/migrate_pmid_to_uid.go
tools/migrate_sessions_expand/migrate_sessions_expand.go
tools/permission_gid/permission_gid.go
user/service/service/standard.go

@jh-bate Infer application name from the name of the binary executable

Infer application name from executable

---

CHANGELOG.md
Makefile
README.md
_tools/git/hooks/pre-commit

Remove deprecated git-hooks target; update .PHONY targets

---

CHANGELOG.md
application/version/test/init.go
auth/test/client.go
auth/test/context.go
auth/test/details.go
auth/test/init.go
config/test/init.go
config/test/reporter.go
data/deduplicator/test/factory.go
data/deduplicator/test/init.go
data/store/test/init.go
data/store/test/session.go
data/test/datum.go
data/test/deduplicator.go
data/test/init.go
log/json/serializer_test.go
log/logger_test.go
test/init.go
test/mock.go
test/mongo/init.go
test/rest/init.go
test/rest/response_writer.go
user/store/mongo/mongo_test.go

@jh-bate What is says on the tin.

Fix test init and mocks

---

CHANGELOG.md
data/client/client.go
data/client/client_test.go
data/service/api/v1/datasets_data_create.go
data/service/api/v1/datasets_delete.go
data/service/api/v1/datasets_delete_test.go
data/service/api/v1/datasets_update.go
data/service/api/v1/users_data_delete.go
data/service/api/v1/users_data_delete_test.go
data/service/api/v1/users_datasets_create.go
data/service/api/v1/users_datasets_get.go
data/service/api/v1/users_datasets_get_test.go
data/service/api/v1/v1.go
tools/tapi/api/dataset.go
tools/tapi/api/user.go
user/service/api/v1/users_delete.go
user/service/api/v1/users_delete_test.go
user/service/api/v1/v1.go

Update internal URL paths (prefix and params)

---

CHANGELOG.md
auth/client/client.go
client/client.go
service/middleware/header.go
service/middleware/logger.go
service/middleware/trace.go

Fix minor issues with use of defer

---

CHANGELOG.md
auth/service/api/router.go
auth/service/api/status_get.go
auth/service/api/status_get_test.go
data/service/api/standard.go
data/service/api/status_get.go
data/service/api/status_get_test.go
data/service/api/version_get.go
data/service/api/version_get_test.go
notification/service/api/router.go
notification/service/api/status_get.go
notification/service/api/status_get_test.go
task/service/api/router.go
task/service/api/status_get.go
task/service/api/status_get_test.go
user/service/api/standard.go
user/service/api/status_get.go
user/service/api/status_get_test.go
user/service/api/version_get.go
user/service/api/version_get_test.go

Consistent route function naming

---

CHANGELOG.md
application/application.go
log/default.go
log/default_test.go
log/json/logger.go
log/json/logger_test.go
log/json/serializer.go
log/log.go
log/logger.go
log/logger_test.go
log/null/logger.go
log/null/serializer.go
sync/sync_suite_test.go
sync/writer.go
sync/writer_test.go
tool/tool.go

Make logger concurrency safe

---

dexcom/dexcom.go
dexcom/egv.go
dexcom/fetch/translate.go

@jh-bate Enforce CGM high and low limits and add annotations.

Add Hi and Lo annotations

---

.golintignore
auth/provider_session.go
auth/restricted_token.go
data/data_set.go
data/data_source.go
data/datum.go
data/storeDEPRECATED/mongo/mongo.go
data/test/datum.go
data/types/base.go
dexcom/client/client.go
dexcom/dexcom.go
dexcom/fetch/runner.go
dexcom/fetch/translate.go
task/task.go

@jh-bate Support for updating data set device id, model, and serial number. Keep accurate records of all devices that went into the data set and each datum, if possible. Add `HasUpdates` function to all `Update` model structs.

Set device id, model, and serial number correctly from Dexcom API

---

dexcom/event.go
dexcom/fetch/translate.go

@jh-bate The eventSubType is optional for *all* events.

Allow valid missing eventSubType for exercise and health eventTypes

---

.golintignore
auth/service/service/client.go
client/client.go
client/client_test.go
data/data_source.go
dexcom/fetch/runner.go
errors/caller.go
oauth/client/client.go
oauth/oauth.go
request/errors.go

@jh-bate Update to properly handle 400 Bad Request response from Dexcom during refresh token authorization process.

Update OAuth error handling; fix error caller generation

---

Dockerfile.auth
Dockerfile.data
Dockerfile.notification
Dockerfile.task
Dockerfile.user

Update Dockerfile to Go 1.9.1; update Dockerfile environment

---

dexcom/device.go

Fix alert settings snooze validation for Dexcom API

---

CHANGELOG.md
dexcom/fetch/runner.go
task/store/mongo/mongo.go

Add fix to handle Dexcom API not correctly reporting daily G5 Mobile devices

---

dexcom/fetch/runner.go

@jh-bate Ignore 2:45am to 3:45am time period where intermittent refresh token failure occur due to Dexcom backups. Known problem for Dexcom.

Avoid time period when Dexcom API refresh token failures occur

---

CHANGELOG.md
auth/service/api/v1/oauth.go
dexcom/calibration.go
dexcom/client/client.go
dexcom/device.go
dexcom/dexcom.go
dexcom/egv.go
dexcom/event.go
dexcom/fetch/runner.go
oauth/client/client.go
oauth/oauth.go
oauth/token/source.go
task/queue/queue.go

@jh-bate Fixes issue with excessive "Login expired - try signing out & in again" messages.

Properly handle expired access tokens from Dexcom API

---

.travis.yml
Makefile

Fix Travis issues with Docker build

---

CHANGELOG.md
data/deduplicator/hash_deactivate_old.go
data/deduplicator/hash_deactivate_old_test.go
migrations/start.sh
services/auth/start.sh
services/data/start.sh
services/notification/start.sh
services/task/start.sh
services/user/start.sh
tools/start.sh

@jh-bate What it says on the tin.

Add LifeScan Verio and Verio Flex to supported devices

---

CHANGELOG.md
client/client.go
client/client_test.go

Strip trailing slashes from client base address

---

CHANGELOG.md
client/client.go
client/client_test.go
request/errors.go
request/errors_test.go

Handle additional client response codes

---

.travis.yml
CHANGELOG.md
Makefile

@jh-bate Not used right now, but will be by Auth0 management tool.

Various Makefile updates

---

CHANGELOG.md
application/application.go
application/application_test.go
application/runner.go
application/runner_test.go
application/test/runner.go
application/version/reporter.go
migrations/20160823040044_data_gid_to_uid/20160823040044_data_gid_to_uid.go
migrations/20160923093857_session_expand/20160923093857_session_expand.go
migrations/20170228082050_metadata_pmid_to_uid/20170228082050_metadata_pmid_to_uid.go
migrations/20170809093903_data_deduplicator_descriptor/20170809093903_data_deduplicator_descriptor.go
services/auth/auth.go
services/data/data.go
services/notification/notification.go
services/task/task.go
services/user/user.go
tool/tool.go
tools/metric_hash/metric_hash.go
tools/permission_gid/permission_gid.go

Application package updates and tests; remove tool verbose flag

---

auth/service/service/service.go

Log error if Dexcom provider could not be created

---

CHANGELOG.md
data/blood/glucose/test/target.go
data/deduplicator/hash_deactivate_old_test.go
data/deduplicator/truncate_test.go
data/test/deduplicator_descriptor.go
data/types/basal/test/suppressed.go
data/types/bolus/combination/test/combination.go
data/types/bolus/extended/test/extended.go
data/types/bolus/normal/test/normal.go
data/types/device/status/test/status.go
data/types/test/base.go
errors/test/errors.go
test/internet/internet.go
test/string.go
test/time.go

@jh-bate Mostly additional test helpers. Minor test updates. No actual code changes.

Additional test helpers

---

CHANGELOG.md
config/env/reporter_test.go
page/pagination_test.go
service/api/auth_test.go
structure/parser/array_parser_test.go
structure/parser/object_parser_test.go
structure/validator/array_test.go
structure/validator/bool_test.go
structure/validator/float64_test.go
structure/validator/int_test.go
structure/validator/object_test.go
structure/validator/string_array_test.go
structure/validator/string_test.go
structure/validator/time_test.go

Refactor error expectations using new test helpers

---

CHANGELOG.md
store/mongo/config.go
store/mongo/mongo.go

Log debug mongo connection configuration

---

CHANGELOG.md
data/types/upload/upload_test.go

Add tests for missing upload id

---

data/types/settings/pump/basal_schedule.go
data/types/settings/pump/basal_schedule_test.go
data/types/settings/pump/pump_test.go

@jh-bate Refactoring the data validation introduced an extra layer of serialization. Remove that extra layer. (It showed up in the mongo database.)

Fix pump settings serialization

---

CHANGELOG.md
Makefile
auth/client/external.go
client/config.go
config/config.go
config/env/reporter.go
config/env/reporter_test.go
config/errors.go
config/errors_test.go
config/test/reporter.go
platform/config.go
platform/mutator_test.go
service/server/config.go
store/mongo/config.go
task/queue/queue.go
tool/mongo/tool.go
tool/mongo/tool_test.go
tool/tool.go
tool/tool_test.go

Allow additional scopes on tools

---

CHANGELOG.md
data/service/api/v1/datasets_data_create.go
data/service/api/v1/users_datasets_create.go

@jh-bate Immediately exit once an error response has been sent.

Return on validation or normalization error after sending response

---

CHANGELOG.md
LICENSE
data/storeDEPRECATED/mongo/mongo.go

Return only active data sets

---

CHANGELOG.md
data/types/blood/glucose/continuous/continuous_test.go
data/types/blood/glucose/glucose_test.go
data/types/blood/glucose/selfmonitored/selfmonitored_test.go
data/types/calculator/calculator_test.go
data/types/device/calibration/calibration_test.go
data/types/settings/pump/insulin_sensitivity_test.go
data/types/settings/pump/pump_test.go

Remove unnecessary test expectations

---

CHANGELOG.md
data/types/factory/factory.go
data/types/settings/cgm/cgm.go
data/types/settings/cgm/cgm_suite_test.go
data/types/settings/cgm/cgm_test.go
data/types/settings/cgm/level_alert.go
data/types/settings/cgm/level_alert_test.go
data/types/settings/cgm/out_of_range_alert.go
data/types/settings/cgm/out_of_range_alert_test.go
data/types/settings/cgm/rate_alert.go
data/types/settings/cgm/rate_alert_test.go

@jh-bate Add `cgmSettings` data type.

Add new cgm settings data model type

---

CHANGELOG.md
data/service/api/v1/users_datasets_get.go
data/storeDEPRECATED/mongo/mongo.go
data/storeDEPRECATED/store.go
data/storeDEPRECATED/store_test.go

@jh-bate Replace old code with new parsing mechanism.

Refactor data set filter to use new query parser

---

CHANGELOG.md
data/parser.go
data/parser/parser_suite_test.go
data/parser/standard_array.go
data/parser/standard_array_test.go
data/parser/standard_object.go
data/parser/standard_object_test.go
service/errors.go
service/errors_test.go

Add time parsing to data parser

---

CHANGELOG.md
data/deduplicator.go
data/deduplicator_test.go
data/types/base_test.go
data/types/test/test.go
data/types/upload/client.go
data/types/upload/client_test.go
data/types/upload/upload.go
data/types/upload/upload_test.go
test/clone.go
test/http/http.go
test/internet/internet.go
validate/validate.go
validate/validate_suite_test.go
validate/validate_test.go

Error on duplicate device manufacturers or tags; add validations and tests

---

CHANGELOG.md
data/types/insulin/dose.go
data/types/insulin/dose_test.go
data/types/insulin/insulin.go
data/types/insulin/insulin_test.go

Add new fields to insulin data type

---

CHANGELOG.md
structure/validator/errors.go
structure/validator/errors_test.go

@jh-bate Some of the error messages being returned were returning odd values (like "1.234567e+06" which should be just "1234567"). This PR fixes all of those oddities (at least that I know).

Update string generation for structure validation error detail

---

CHANGELOG.md
data/types/insulin/insulin.go
data/types/insulin/insulin_test.go

Add concentration field to insulin data type

---

CHANGELOG.md
data/types/state/reported/reported_test.go
data/types/state/reported/state.go
data/types/state/reported/state_test.go
dexcom/fetch/translate.go

@jh-bate Fill out the remaining fields for the reported state data type per https://docs.google.com/document/d/1Q2H9fejBI3nUT7Y8_NwI1c7z9l1ByilPFs7o3ApRZNQ/edit?usp=sharing.

Add new fields to reported state data type

---

CHANGELOG.md
data/types/food/amount.go
data/types/food/amount_test.go
data/types/insulin/insulin.go
data/types/insulin/insulin_test.go
data/types/water/amount.go
data/types/water/amount_test.go
data/types/water/water.go
data/types/water/water_suite_test.go
data/types/water/water_test.go

@jh-bate Add water data type per https://docs.google.com/document/d/1Q2H9fejBI3nUT7Y8_NwI1c7z9l1ByilPFs7o3ApRZNQ/edit?usp=sharing.

Add water data type

---

CHANGELOG.md
data/types/activity/physical/distance.go
data/types/activity/physical/distance_test.go
data/types/activity/physical/duration.go
data/types/activity/physical/duration_test.go
data/types/activity/physical/elevation_change.go
data/types/activity/physical/elevation_change_test.go
data/types/activity/physical/energy.go
data/types/activity/physical/energy_test.go
data/types/activity/physical/flight.go
data/types/activity/physical/flight_test.go
data/types/activity/physical/physical.go
data/types/activity/physical/physical_test.go
data/types/activity/physical/step.go
data/types/activity/physical/step_test.go

@jh-bate Fill out the physical activity data type per https://docs.google.com/document/d/1Q2H9fejBI3nUT7Y8_NwI1c7z9l1ByilPFs7o3ApRZNQ/edit?usp=sharing.

Add new fields to physical activity data type

---

.golintignore
CHANGELOG.md
data/types/insulin/concentration.go
data/types/insulin/concentration_test.go
data/types/insulin/formulation.go
data/types/insulin/formulation_test.go
data/types/insulin/insulin.go
data/types/insulin/insulin_test.go
data/types/insulin/insulin_type.go
data/types/insulin/insulin_type_test.go
data/types/insulin/mix.go
data/types/insulin/mix_test.go
data/types/insulin/test/concentration.go
data/types/insulin/test/formulation.go
data/types/insulin/test/insulin_type.go
data/types/insulin/test/mix.go

@jh-bate After discussion with several folks, we need to flesh out the concentration into a more complex data structure. Documented in https://docs.google.com/document/d/1Q2H9fejBI3nUT7Y8_NwI1c7z9l1ByilPFs7o3ApRZNQ/edit?usp=sharing.

Refactor insulin data type to add formulation and mix

---

CHANGELOG.md
data/types/settings/pump/basal.go
data/types/settings/pump/basal_rate_maximum.go
data/types/settings/pump/basal_rate_maximum_test.go
data/types/settings/pump/basal_temporary.go
data/types/settings/pump/basal_temporary_test.go
data/types/settings/pump/basal_test.go
data/types/settings/pump/bolus.go
data/types/settings/pump/bolus_amount_maximum.go
data/types/settings/pump/bolus_amount_maximum_test.go
data/types/settings/pump/bolus_combination.go
data/types/settings/pump/bolus_combination_test.go
data/types/settings/pump/bolus_test.go
data/types/settings/pump/display.go
data/types/settings/pump/display_test.go
data/types/settings/pump/insulin.go
data/types/settings/pump/insulin_test.go
data/types/settings/pump/pump.go
data/types/settings/pump/pump_test.go

@jh-bate Fill out pump settings data type per https://docs.google.com/document/d/1Q2H9fejBI3nUT7Y8_NwI1c7z9l1ByilPFs7o3ApRZNQ/edit?usp=sharing.

Add new fields to pump settings data type

---

CHANGELOG.md
data/types/settings/cgm/cgm.go
data/types/settings/cgm/cgm_test.go

@jh-bate Fill out cgm settings data type per https://docs.google.com/document/d/1Q2H9fejBI3nUT7Y8_NwI1c7z9l1ByilPFs7o3ApRZNQ/edit?usp=sharing.

Add new fields to cgm settings data type

---

CHANGELOG.md
data/types/upload/upload.go

@jh-bate Accidentally specified wrong type for "upload" records.

Fix bug in upload data type with check against incorrect type

---

CHANGELOG.md
structure/test/validatable_with_int.go
structure/validator.go
structure/validator/adapter.go
structure/validator/adapter_test.go
structure/validator/array.go
structure/validator/bool.go
structure/validator/float64.go
structure/validator/int.go
structure/validator/object.go
structure/validator/string.go
structure/validator/string_array.go
structure/validator/time.go

@jh-bate Define specific validation funcs as actual types. Add ValidatableWithInt transformation wrapper for validators. Both used in future commits.

Refactor structure validator to define new function types

---

CHANGELOG.md
data/types/settings/pump/bolus.go
data/types/settings/pump/bolus_calculator.go
data/types/settings/pump/bolus_calculator_test.go
data/types/settings/pump/pump.go

@jh-bate What it says on the tin.

Add bolus calculator enabled field to pump settings data model

---

CHANGELOG.md
data/types/activity/physical/lap.go
data/types/activity/physical/lap_test.go
data/types/activity/physical/physical.go
data/types/activity/physical/physical_test.go

@jh-bate Per request from latest data model review at offsite.

Add lap data to physical activity data model

---

.golintignore
CHANGELOG.md
auth/service/api/status_get_test.go
log/json/serializer_test.go
request/responder.go
service/api/auth_test.go
service/context/context_test.go
service/context/responder_test.go
service/middleware/access_log_test.go
service/middleware/auth_test.go
service/middleware/logger_test.go
service/middleware/recover_test.go
service/middleware/trace_test.go
test/rest/response_writer.go

* Update test ResponseWriter to implement http.ResponseWriter interface
* Write new line after JSON response
* Check all test ResponseWriter expectations
@jh-bate

Refactor responder to log error if failure to write response

---

CHANGELOG.md
data/types/food/food_test.go
data/types/food/ingredient_test.go
data/types/insulin/test/compound.go
data/types/insulin/test/formulation.go

Rename array depth to array depth limit in test helpers

---

.travis.yml
CHANGELOG.md
Makefile

Update Makefile to exclude .git directory from CompileDaemon

---

.travis.yml
CHANGELOG.md
Dockerfile.auth
Dockerfile.data
Dockerfile.migrations
Dockerfile.notification
Dockerfile.task
Dockerfile.tools
Dockerfile.user

Update to Go 1.10.2

---

data/types/upload/upload_test.go
test/random.go

@jh-bate Only updates to tests and test support.

Add and update random test data generators

---

CHANGELOG.md
config/errors_test.go
data/types/settings/cgm/cgm_test.go
errors/test/errors.go
request/errors_test.go
structure/parser/errors_test.go
structure/validator/errors_test.go

@jh-bate Minor refactor to pull out common test functionality into common function in `errors` test package.

Refactor common error test expectations

---

CHANGELOG.md
auth/client/client.go
auth/client/external.go
auth/service/service/client.go
auth/service/service/service.go
client/client.go
client/client_test.go
client/config.go
client/config_test.go
data/client/client.go
data/client/client_test.go
data/service/service/standard.go
metric/client/client.go
metric/client/client_test.go
notification/client/client.go
notification/client/client_test.go
oauth/client/client.go
platform/client.go
platform/client_test.go
platform/config.go
platform/config_test.go
request/request.go
service/service/DEPRECATED_service.go
service/service/DEPRECATED_service_test.go
service/service/authenticated.go
task/client/client.go
task/service/service/service.go
user/client/client.go
user/service/service/standard.go

* Add streamed response from client in addition to existing data response
* Add ability to specify authorization mechanism at client creation
* Improve client tests
* Remove client timeout configuration, as unused
@jh-bate Clean up how clients function against other services.

Refactor client functionality

---

CHANGELOG.md
auth/client/client.go
data/client/client.go
data/data_source.go
data/service/api/v1/data_set.go
data/service/api/v1/datasets_data_create.go
data/service/api/v1/datasets_delete.go
data/service/api/v1/datasets_update.go
data/service/api/v1/users_datasets_create.go
data/service/api/v1/users_datasets_get.go
dexcom/fetch/runner.go
errors/errors.go
oauth/oauth.go
request/errors.go
request/errors_test.go
task/client/client.go
user/client/client.go
user/service/api/v1/users_delete.go

@jh-bate Updates to general errors in system.

Add shortcuts for request error comparisons

---

CHANGELOG.md
auth/client/client_test.go
auth/service/service/service_test.go
config/env/reporter_test.go
data/blob_test.go
data/client/client_test.go
data/deduplicator/hash_test.go
data/service/route_test.go
metric/client/client_test.go
net/net_test.go
notification/service/service/service_test.go
permission/store/mongo/config_test.go
service/api/auth_test.go
service/error_test.go
service/server/config_test.go
service/service/DEPRECATED_service_test.go
store/mongo/config_test.go
task/service/service/service_test.go
user/client/client_test.go
user/service/route_test.go
user/store/mongo/config_test.go

@jh-bate Just few steps towards generally cleaning up and simplifying tests.

Minor test refactor and cleanup

---

CHANGELOG.md
structure/structure.go
structure/structure_test.go

Update structure parameter source to return unchanged if multiple references applied

---

CHANGELOG.md
env.test.sh

Restrict test environment variables to only necessary

---

.gitignore
CHANGELOG.md
Dockerfile.blob
blob/service/service.go
blob/service/service_test.go
client/client.go
client/client_test.go
env.sh
service/middleware/trace.go

* Add Dockerfile and config for running blob service
* Remove check for correct content type from legacy service responses
* Fix incorrect usage of test package in trace middleware
* Minor updates to blob service configuration
@jh-bate

Enable blob service for Docker and minor updates

---

CHANGELOG.md
data/types/insulin/insulin.go
data/types/insulin/insulin_test.go

Allow insulin data type without dose

---

CHANGELOG.md
data/types/activity/physical/physical.go
data/types/activity/physical/physical_test.go

Allow physical activity other field as optional

---

CHANGELOG.md
blob/store/structured/mongo/mongo_test.go
dexcom/fetch/runner.go
tools/dump_users/dump_users.go

@jh-bate A baseline tool to dump all of the users. Specific tools using custom queries will be based off this.

Dump users tool

---

CHANGELOG.md
structure/validator.go
structure/validator/string_array.go
structure/validator/string_array_test.go

Add EachUsing to string array structure validator

---

CHANGELOG.md
user/client.go
user/client/client.go
user/client/client_test.go
user/test/client.go

Add EnsureAuthorized to user client

---

CHANGELOG.md
blob/blob_test.go
blob/client/client_test.go
blob/service/api/v1/v1_test.go
blob/service/client_test.go
blob/store/structured/mongo/mongo_test.go
blob/test/blob.go
data/client/client_test.go
data/deduplicator/hash_deactivate_old_test.go
data/deduplicator/hash_test.go
data/deduplicator/truncate_test.go
data/types/base_test.go
data/types/test/base.go
data/types/upload/upload_test.go
user/client/client_test.go
user/test/user.go

@jh-bate Standardizing on using Random* test functions to generate sample data.

Replace user.NewID with userTest.RandomID in tests

---

CHANGELOG.md
application/runner_test.go
blob/client/client_test.go
blob/service/api/v1/v1_test.go
blob/service/client_test.go
blob/store/unstructured/unstructured_test.go
client/client_test.go
data/normalizer/normalizer_test.go
dexcom/fetch/runner.go
errors/errors.go
errors/test/errors.go
id/id_test.go
log/logger.go
request/request_test.go
service/middleware/auth_test.go
store/unstructured/file/file_test.go
store/unstructured/s3/s3_test.go
structure/base/base_test.go
structure/normalizer/normalizer_test.go
structure/parser/array_parser_test.go
structure/parser/object_parser_test.go
structure/validator/validator_test.go

@jh-bate Mostly move errorsTest.NewError to errorsTest.RandomError.

Update error test helper functions

---

CHANGELOG.md
blob/blob_test.go
blob/client/client_test.go
blob/service/api/v1/v1_test.go
blob/service/client_test.go
blob/store/structured/mongo/mongo_test.go
blob/test/blob.go

@jh-bate More test helper updates.

Replace blob.NewID with blobTest.RandomID in tests

---

CHANGELOG.md
blob/blob.go
blob/blob_test.go
blob/client/client_test.go
blob/store/structured/mongo/mongo.go
blob/test/blob.go

@jh-bate A bunch of small changes to finalize the blob service which I'll be using as a template of sorts.

Cleanup blob service and tests

---

CHANGELOG.md
data/deduplicator/hash_deactivate_old_test.go
data/deduplicator/truncate_test.go
data/test/data.go
data/test/data_set.go
data/types/base_test.go
data/types/calculator/calculator_test.go
data/types/common/association/association_test.go
data/types/common/association/test/association.go
data/types/device/alarm/alarm_test.go
data/types/device/reservoirchange/reservoirchange_test.go
data/types/test/base.go

@jh-bate More test helper updates.

Replace data.NewID with dataTest.RandomID in tests

---

CHANGELOG.md
auth/provider_session.go
auth/test/provider_session.go
auth/test/restricted_token.go

Add helper functions for auth types

---

CHANGELOG.md
auth/service/service/service.go
blob/service/service.go
notification/service/service/service.go
service/api.go
service/api/api.go
service/test/api.go
task/service/service/service.go

@jh-bate Pull out common functionality into abstract service.

Refactor InitializeRouters to encapsulate common functionality

---

CHANGELOG.md
blob/blob.go
blob/blob_test.go
blob/service/client/client.go
blob/service/client/client_test.go

@jh-bate Should have had this in earlier. Make sure blobs cannot be over 100MB in size.

Add blob size maximum

---

CHANGELOG.md
data/storeDEPRECATED/mongo/mongo_test.go
data/types/base.go

@jh-bate Fix previously commented out tests for the data store. (They were commented out a while back due to some general store changes. This just gets them working again.)

Fix data store tests

---

CHANGELOG.md
data/service/service/standard.go

@jh-bate Fixed one bug found in manual testing. No easy way to add a unit test.

Fix data service data source client

---

CHANGELOG.md
data/types/base_test.go
data/types/common/location/gps_test.go
data/types/common/origin/origin.go
data/types/common/origin/origin_test.go
data/types/common/origin/test/origin.go

* Add origin type "service"
* Add origin payload
* Update origin name to validate as string with maximum length
@jh-bate

Update origin structure

---

CHANGELOG.md
data/data.go
data/service/api/v1/datasets_data_delete.go
data/service/api/v1/v1.go
data/storeDEPRECATED/mongo/mongo.go
data/storeDEPRECATED/mongo/mongo_test.go
data/storeDEPRECATED/store.go
data/storeDEPRECATED/test/data_session.go
data/types/upload/client_test.go
data/types/upload/test/client.go
data/types/upload/test/upload.go
data/types/upload/upload_test.go

Add API to batch delete data set data

---

data/deduplicator/base.go
data/deduplicator/continuous.go

Fix registered deduplicator check

---

CHANGELOG.md
data/deduplicator/continuous_origin.go
data/types/base.go
data/types/common/origin/origin.go

Add direct access to data origin

---

CHANGELOG.md
data/types/food/carbohydrate.go
data/types/food/carbohydrate_test.go
data/types/food/fat.go
data/types/food/fat_test.go
data/types/food/protein.go
data/types/food/protein_test.go
dexcom/fetch/translate.go

Use float64 for food data type values

---

CHANGELOG.md
data/source/source.go
data/source/source_test.go
data/source/store/structured/mongo/mongo.go
data/source/store/structured/mongo/mongo_test.go
data/source/test/source.go
dexcom/provider/provider.go

* Add optional provider session id to data source update
* Add new provider session id to data source after reconnecting Dexcom API
@jh-bate

Update data source provider session id

---

CHANGELOG.md
dexcom/calibration.go
dexcom/device.go
dexcom/device_test.go
dexcom/egv.go
dexcom/event.go

Add meta to Dexcom data to assist with debugging validation errors

---

CHANGELOG.md
data/data.go
data/deduplicator/deduplicator.go
data/deduplicator/deduplicator/base.go
data/deduplicator/deduplicator/base_test.go
data/deduplicator/deduplicator/data_set_delete_origin_test.go
data/deduplicator/deduplicator/device_deactivate_hash_test.go
data/deduplicator/deduplicator/device_truncate_data_set_test.go
data/deduplicator/deduplicator/none_test.go
data/deduplicator/test/deduplicator.go
data/service/api/v1/datasets_data_delete.go
data/storeDEPRECATED/mongo/mongo.go
data/storeDEPRECATED/mongo/mongo_test.go
data/storeDEPRECATED/store.go
data/storeDEPRECATED/test/data_session.go
data/test/data.go

@jh-bate Just a rename and no other changes.

Rename data.Delete to data.Selector for more general usage

---

CHANGELOG.md
blob/store/structured/mongo/mongo.go
blob/store/structured/mongo/mongo_test.go
data/blob.go
data/source/store/structured/mongo/mongo.go
data/types/common/association/association.go
data/types/common/association/test/association.go
data/types/food/ingredient.go
data/types/insulin/compound.go
data/types/settings/pump/basal_rate_start.go
data/types/settings/pump/blood_glucose_target_start.go
data/types/settings/pump/carbohydrate_ratio_start.go
data/types/settings/pump/insulin_sensitivity_start.go
data/types/state/reported/state.go
store/structured/mongo/mongo.go
structure/validator/array.go
structure/validator/object.go
structure/validator/string.go
structure/validator/string_array.go
test/random.go
tools/tapi/api/request.go
tools/tapi/api/response.go

Refactor for code consistency

---

CHANGELOG.md
data/deduplicator/deduplicator/base.go
data/deduplicator/deduplicator/base_test.go
data/deduplicator/deduplicator/data_set_delete_origin_test.go
data/deduplicator/deduplicator/device_deactivate_hash_test.go
data/deduplicator/deduplicator/device_truncate_data_set_test.go
data/deduplicator/deduplicator/none_test.go
data/service/api/v1/users_datasets_create.go

* Return updated data set after creation
* Remove unnecessary condition when opening deduplicator for data set
@jh-bate

Fix minor issues when opening data set deduplicator

---

Dockerfile.auth
Dockerfile.blob
Dockerfile.data
Dockerfile.migrations
Dockerfile.notification
Dockerfile.task
Dockerfile.tools
Dockerfile.user

- Move multiple RUN into a single RUN to reduce number of image layers
- Run apk update and apk upgrade to get latest OS patches

Dockerfile updates

---

CHANGELOG.md
data/storeDEPRECATED/mongo/mongo.go
data/storeDEPRECATED/test/data_session.go

@jh-bate You already did this review, but I had to rearrange some branches in order to fix a breaking build.

Remove unused code in data store mongo implementation

---

CHANGELOG.md
migration/mongo/migration.go
migrations/20160823040044_data_gid_to_uid/20160823040044_data_gid_to_uid.go
migrations/20160923093857_session_expand/20160923093857_session_expand.go
migrations/20170228082050_metadata_pmid_to_uid/20170228082050_metadata_pmid_to_uid.go
migrations/20170809093903_data_deduplicator_descriptor/20170809093903_data_deduplicator_descriptor.go
migrations/20180824161319_data_deduplicator_descriptor/20180824161319_data_deduplicator_descriptor.go
tool/mongo/tool.go
tool/tool.go
tools/dump_users/dump_users.go
tools/metric_hash/metric_hash.go
tools/permission_gid/permission_gid.go

Rename local variable name context to ctx for consistency

---

CHANGELOG.md
tools/benchmark_data_store/benchmark_data_store.go

@jh-bate Just a tool for testing database performance. Will never be deployed.

Add data store benchmark tool

---

CHANGELOG.md
client/client.go
client/client_test.go
test/request.go

Update client package tests to latest best practices

---

CHANGELOG.md
platform/client_test.go

Update platform package tests to latest best practices

---

CHANGELOG.md
oauth/client/client.go
oauth/client/client_suite_test.go
oauth/client/client_test.go
oauth/test/http_client_source.go
oauth/test/token_source.go
oauth/test/token_source_source.go

Update oauth/client package tests to latest best practices

---

CHANGELOG.md
pointer/equal.go
pointer/equal_test.go

Add pointer.Equal functions

---

CHANGELOG.md
data/types/insulin/formulation_test.go
data/types/insulin/simple.go
data/types/insulin/simple_test.go
dexcom/alert.go
dexcom/fetch/translate.go

@pazaan Final (hopefully) updates for Dexcom API due to unexpected data from API.

Dexcom API fixes

---

CHANGELOG.md
data/storeDEPRECATED/mongo/mongo.go

@pazaan Same as already approved PR https://github.com/tidepool-org/platform/pull/377. Moving to a develop branch so created a new PR to keep it clean.

Add user id to ArchiveDeviceDataUsingHashesFromDataSet selector to properly use indexes

---

CHANGELOG.md
auth/client/client_test.go
auth/service/service/service_test.go
message/store/mongo/mongo_test.go
notification/service/service/service_test.go
permission/store/mongo/mongo_test.go
profile/store/mongo/mongo_test.go
session/store/mongo/mongo_test.go
synctask/store/mongo/mongo_test.go
task/client/client_test.go
task/service/api/api.go
task/service/api/api_test.go
task/service/api/v1/v1_test.go
task/service/service/service_test.go
task/service/test/service.go
task/store/mongo/mongo_test.go
user/store/mongo/mongo_test.go

@pazaan Fixing disabled tests tech debt from initial Dexcom API integration.

Fix unused tests

---

CHANGELOG.md
data/types/insulin/dose.go
data/types/insulin/dose_test.go
data/types/insulin/test/dose.go
dexcom/alert.go
dexcom/alert_test.go
dexcom/calibration.go
dexcom/calibration_test.go
dexcom/egv.go
dexcom/egv_test.go
dexcom/event.go
dexcom/event_test.go
dexcom/fetch/translate.go
dexcom/test/alert.go

* Relax Dexcom API validations to match Tidepool data model validations
* Rename insulin dose constants to properly include units
@pazaan

Relax Dexcom API validations to match Tidepool data model validations

---

data/types/blood/glucose/selfmonitored/selfmonitored.go
data/types/blood/glucose/selfmonitored/selfmonitored_test.go

What it says on the tin. Required for https://trello.com/c/O9i3tqCA.

Adding a 'scanned' option to smbg.subType

---

Makefile

Update the Makefile to build Docker images for
all services that pass unit test and to tag and
to push them to DockerHub.  Tags will contain
the branch (or tag) and the Git SHA.
@pazaan - Tested! :)

Build, tag, and push Docker images for all successful pushes.

---

CHANGELOG.md

Review the merge from the release branch back into the `develop` branch.

Release 1.32.1

---

Dockerfile.auth
Dockerfile.blob
Dockerfile.data
Dockerfile.image
Dockerfile.migrations
Dockerfile.notification
Dockerfile.task
Dockerfile.tools
Dockerfile.user

Part of [WEB-210]
To be used alongside tidepool-org/development#24
[WEB-210]: https://tidepool.atlassian.net/browse/WEB-210

Updates to run in local Tilt/K8s environment [WEB-210]

---

data/types/device/devicesensor/devicesensor.go
data/types/device/devicesensor/devicesensor_suite_test.go
data/types/device/devicesensor/devicesensor_test.go

Add device sensor event to data model

[BACK-812] Add device sensor event to data model

---

data/types/device/devicesettingschange/devicesettingschange.go
data/types/device/devicesettingschange/devicesettingschange_suite_test.go
data/types/device/devicesettingschange/devicesettingschange_test.go
data/types/device/devicesettingschange/settingschange.go
data/types/device/devicesettingschange/settingschange_test.go

Adds device settings change model

[BACK-813] Add device settings change model to data platform

---

data/types/food/nutrition.go
data/types/food/nutrition_test.go

renamed to estimatedAbsorptionDuration as per Device Model meeting

renamed absorptionDuration [BACK-810]

---

service/api/api.go
task/service/service/service.go

@tjotala This is an example of a change we would want to push out quickly.  We need a process that enables that.  Right now, I am under the impression that I have to create a Jira ticket just to get this approved.

Suppress excess logging, add error output

---

data/types/blood/glucose/continuous/continuous.go
data/types/blood/glucose/continuous/continuous_test.go
data/types/blood/glucose/continuous/rate.go
data/types/blood/glucose/continuous/rate_test.go
data/types/blood/glucose/continuous/trend.go
data/types/blood/glucose/continuous/trend_test.go

First pass at new trend rate structure

[BACK-811] initial pass at new trend rate structure

---

data/service/service/standard.go
data/storeDEPRECATED/mongo/mongo.go
data/storeDEPRECATED/store.go
data/storeDEPRECATED/test/data_session.go

[BACK-355] Add indexes for performance

---

data/types/calculator/calculator.go
data/types/calculator/calculator_test.go

Add carb unit field so UI can calculate carbs correctly

#BACK-1162 add Carb Unit field to calculator object

---

structure/parser.go

Simplified `ForgivingTimeString` code

---

service/middleware/access_log.go
store/unstructured/s3/s3.go
store/unstructured/s3/s3_test.go

And added bucket name to error message.

Filter out Gloo calls for swagger docs.  

---

data/types/dosingdecision/carbohydrates_on_board_test.go
data/types/dosingdecision/insulin_on_board.go
data/types/dosingdecision/insulin_on_board_test.go
data/types/dosingdecision/recommended_basal_test.go
data/types/dosingdecision/recommended_bolus_test.go

- Update dosing decision tests to test value boundaries

Update dosing decision to allow negative insulin on board

---

Dockerfile.auth
Dockerfile.blob
Dockerfile.data
Dockerfile.image
Dockerfile.migrations
Dockerfile.notification
Dockerfile.task
Dockerfile.tools
Dockerfile.user

Speeds up the build process by 2-3 minutes by reusing common images and layers more effectively.

Docker build improvements

---

prescription/api/v1_test.go

A new test case that was added in #503 failed, because of some code changes in #500 which were merged to master first. This prevented the [merge build](https://travis-ci.com/github/tidepool-org/platform/builds/174395253) from completing successfully.

[BACK-1468] Fix broken unit test

---

migrations/back-1572/back-1572.go

The migration was attempting to change the Mongo Object ID (`_id`) as
part of a regular update. However, Object ID is immutable, meaning that
to resolve this issue, we needed to add a copy of the existing object with
the new Object ID, and archive the old one.
* Fixes [BACK-1572]
[BACK-1572]: https://tidepool.atlassian.net/browse/BACK-1572

[BACK-1572] Migrate documents requiring new Object ID

---

data/blood/glucose/target.go
data/blood/glucose/test/target.go
data/types/settings/pump/blood_glucose_target_start.go
devices/validation.go
prescription/service/validator.go
prescription/settings.go
prescription/settings_test.go
prescription/test/prescription.go

- Adds pre-meal temporary correction range 
- Adds workout temporary correction range
- Adds validation for temporary corrections according to [Therapy Settings Document](https://docs.google.com/document/d/1uKTktpTe8HiKQjyUvljhcE_yHlKfYAaEAMoQDmpCHdo/edit)

[BACK-1532] Add prescription temporary correction ranges

---

prescription/service/validator.go
prescription/settings.go
prescription/settings_test.go

- Remove legacy validation logic
- Use correct device absolute bounds

Fix validation of workout and pre-meal correction ranges

---

data/store/mongo/mongo.go
data/store/mongo/mongo_test.go

This order matches the production index

Reorder DeduplicatorHash index partial filter expression attributes

---

prescription/calculator.go
prescription/calculator_test.go
prescription/revision.go
prescription/revision_test.go
prescription/test/prescription.go

See [BACK-1925](https://tidepool.atlassian.net/browse/BACK-1925) for details.

[BACK-1925] Add calculator fields to prescription revisions

---

prescription/api/v1_test.go

This fixes the flaky test which failed [this](https://travis-ci.com/github/tidepool-org/platform/builds/230218584) build

Fix randomly failing test

---

clinics/mock.go
clinics/service.go
prescription/service/service.go
prescription/service/service_suite_test.go
prescription/service/service_test.go
prescription/store/test/prescription_repository.go
prescription/store/test/store.go

The snyk failure is addressed in #573

[BACK-1931] Share patient account with clinic when claiming prescription

---

data/store/mongo/mongo_data.go
data/types/base.go
task/summary/updaterunner.go

Ensure outdated summaries are not created for users uploading very old or future data
Raise summary calculation batch size and lower interval

Summary service tuning for live data Part 2

---

data/store/mongo/mongo_data.go

fix distinct cgm users query to not use $or for dates and cause the db to spin for hours

Distinct query with $or time fields causes unoptimized query

---

Dockerfile.tools
data/datum.go
data/store/mongo/mongo_data.go
data/store/mongo/mongo_test.go
tools/ashrc

Update modifiedTime on all data modifications - insert, update, delete.

[Back-2384] update device data modified time.

---

data/summary/summary.go
dexcom/fetch/runner.go
task/queue/queue.go
task/store/mongo/mongo.go
task/store/store.go
task/summary/backfillrunner.go
task/summary/task.go
task/summary/update.go
task/summary/updaterunner.go
task/task.go

better manage memory during summary backfill
add configuration to summary tasks for interval and batch size

[BACK-2537] Improve memory management and summary task configuration

---

README.md

Some additional notes for setting up mongodb.

README.md updates for mongodb config

---

data/summary/types/bgm.go
data/summary/types/cgm.go
data/summary/types/summary.go
data/summary/types/test/summary.go

Namely, addBinAfter, addBinBefore, and replaceBin.
I found this breakdown a little easier to reason about, as it separates the if-then structures and exposes what I feel is a more obvious, and more task-oriented flow.
It might also be interesting too, to have a "readjust" function, that given a slice of buckets, simply re-orders them and inserts/removes gaps as necessary. Then AddBin just becomes something like:
buckets = append(buckets, newBucket)
readjustBuckets(buckets)
The signature for removeExcessBuckets has an extra argument, because I couldn't quite figure out how to make the compiler happy without it.

break AddBin down into smaller functions

---

alerts/client.go
data/service/api/v1/alerts.go
data/service/api/v1/alerts_test.go
data/service/api/v1/mocks/context.go

This change was requested during review of the matching documentation update,
BACK-2500

changes alerts endpoints to match API docs

---

Makefile
auth/auth.go
client/config.go
data/datum.go
data/service/api/v1/datasets_data_create.go
data/service/api/v1/datasets_data_create_provenance_test.go
data/service/api/v1/users_datasets_create.go
data/service/api/v1/users_datasets_create_test.go
data/test/datum.go
data/types/base.go

inject a provenance subdocument to device data

---

data/store/mongo/mongo_data.go
data/store/mongo/mongo_data_set.go
data/store/mongo/mongo_datum.go
data/store/store.go

Since all uploads are already migrated, this does not change the existing output of any function. As spotted by @Roukoswarf

Clean up some remaining dual reads for datasets. 

---

alerts/config.go
alerts/config_test.go

This will be used later to limit the data evaluated for care partner alerts.
BACK-2554
BACK-3047

adds UploadID to alerts.Config

---

Makefile
blob/store/structured/mongo/blob_repository_test.go
data/store/mongo/mongo_test.go
data/summary/store/store_test.go
prescription/store/mongo/prescription_repository_test.go
prescription/store/mongo/store_test.go
store/structured/mongo/mongo_test.go

Makefile updates; add ginkgo labels to integration tests

---

task/queue/multi_test.go

There has been discussion of running our test suites via `go test` instead of `ginkgo` to get the package-level parallelism that `go test` offers (and caching!), without having to re-work all of our tests to make use of ginkgo v2's parallelism. To this end, the Makefile previously had a `go-test` recipe added. However, that recipe routinely fails one test in particular.
The test in question was found to be timing-out when run via `go test`. I suspect it's because under `go test` it's run in parallel, and isn't getting as much running time as a result. In any event, giving it more time allows the test to complete successfully (ironic, given that using `go test` is overall faster, at least for me).
I'm not sure that using `go test` is a long-term win over using ginkgo's parallelism though, …

fix for a test that fails under `go test`

---

blob/store/structured/mongo/blob_repository_test.go
blob/store/structured/mongo/devicelogs_repository_test.go
blob/store/structured/mongo/mongo.go
blob/store/structured/mongo/mongo_suite_test.go
blob/store/structured/mongo/mongo_test.go
blob/store/structured/structured_suite_test.go
data/store/mongo/mongo.go
data/store/mongo/mongo_suite_test.go
data/store/mongo/mongo_test.go
data/summary/store/store_suite_test.go
data/summary/store/store_test.go
data/summary/summary_suite_test.go
data/summary/summary_test.go
prescription/store/mongo/mongo_suite_test.go
prescription/store/mongo/prescription_repository_test.go
prescription/store/mongo/store.go
prescription/store/mongo/store_test.go
store/structured/mongo/mongo_test.go
store/structured/mongo/store.go
store/structured/mongo/test/test.go

All my db PRs in one, as requested.

Eric db reuse all in one

---

dexcom/fetch/runner.go

- Fix Dexcom Connection task issue with incorrect id
- https://tidepool.atlassian.net/browse/BACK-3239

BACK-3239] Fix Dexcom Connection task issue with incorrect id

---

data/types/blood/glucose/continuous/continuous.go
data/types/blood/glucose/continuous/continuous_test.go

- Add sample interval and backfilled to cbg data type
- https://tidepool.atlassian.net/browse/BACK-1913

[BACK-1913] Add sample interval and backfilled to cbg data type

---

oauth/provider/provider.go
service/middleware/auth.go
service/middleware/auth_test.go

- Add client id to OAuth provider
- Fix authentication issue with non-Bearer Authorization header
Counterpart to https://github.com/tidepool-org/platform-plugin-abbott/pull/20.

Add client id to OAuth provider and fix authentication issue

---

data/data.go
data/data_test.go
data/datum.go
data/deduplicator/deduplicator/data_set_delete_origin.go
data/deduplicator/deduplicator/data_set_delete_origin_base.go
data/deduplicator/deduplicator/data_set_delete_origin_older.go
data/deduplicator/deduplicator/data_set_delete_origin_older_test.go
data/service/service/standard.go
data/store/mongo/mongo_datum.go
data/store/store.go
data/store/test/data_repository.go

- Handle out-of-order food and bolus data for twiist
- Add new deduplicator
- https://tidepool.atlassian.net/browse/BACK-3514

[BACK-3514] Handle out-of-order food and bolus data for twiist

---

data/service/service/standard.go
data/summary/client/client.go
plugin/abbott/abbott/work/work.go

see https://github.com/tidepool-org/platform-plugin-abbott/pull/24

BACK-3471 summary stats

---

data/service/api/v1/partners.go
data/service/api/v1/v1.go

- Update Abbott sector identifiers
- https://tidepool.atlassian.net/browse/BACK-3394

[BACK-3394] Update Abbott sector identifiers

---

data/service/api/v1/datasets_data_create.go
data/service/api/v1/datasets_data_delete.go
data/service/api/v1/datasets_delete.go
data/service/api/v1/datasets_update.go
data/service/service/client.go
data/service/service/standard.go
data/store/mongo/mongo_data.go
data/store/mongo/mongo_data_set.go
data/store/mongo/mongo_test.go
data/store/store.go
data/store/test/data_repository.go
services/tools/benchmark_data_store/benchmark_data_store.go
services/tools/dump_users/dump_users.go
summary/fetcher/continuous.go
summary/fetcher/fetcher.go

- Refactor data client and repository CreateUserDataSet, GetDataSet, and UpdateDataSet
- Add CreateUserDataSet with user id and data.DataSetCreate
- Replace DataSetRepository GetDataSetByID with GetDataSet
- Connect data service Client UpdateDataSet to repository
- https://tidepool.atlassian.net/browse/BACK-3727

[BACK-3727] Refactor data client and repository CreateUserDataSet, GetDataSet, and UpdateDataSet

---

data/types/device/prime/prime.go
data/types/device/prime/prime_test.go
data/types/device/prime/test/prime.go

- Increase maximum volume for prime device event data
- Update tests and imports
- https://tidepool.atlassian.net/browse/BACK-3750

[BACK-3750] Increase maximum volume for prime device event data

---

dexcom/client/client.go
request/inspector.go

- Create common Prometheus code path response inspector
- Update Dexcom client to use new response inspector
- https://tidepool.atlassian.net/browse/BACK-3729

[BACK-3729] Create common Prometheus code path response inspector

---

data/types/dosingdecision/dosing_decision.go
data/types/dosingdecision/dosing_decision_test.go
data/types/dosingdecision/forecast_blood_glucose.go
data/types/dosingdecision/forecast_blood_glucose_test.go
data/types/dosingdecision/test/blood_glucose.go
data/types/dosingdecision/test/dosing_decision.go
data/types/dosingdecision/test/forecast_blood_glucose.go

- Remove validation on dosing decision blood glucose forecast values
- https://tidepool.atlassian.net/browse/BACK-3836

[BACK-3836] Remove validation on dosing decision blood glucose forecast values

---

data/types/bolus/combination/combination.go
data/types/bolus/combination/combination_test.go
data/types/bolus/combination/test/combination.go
data/types/bolus/extended/extended.go
data/types/bolus/extended/extended_test.go
data/types/bolus/extended/test/extended.go
data/types/bolus/normal/normal.go
data/types/bolus/normal/normal_test.go
data/types/bolus/normal/test/normal.go
data/types/calculator/calculator_test.go
structure/validator.go
structure/validator/duration.go
structure/validator/float64.go
structure/validator/int.go
structure/validator_test.go

- Relax and simplify bolus validation
- https://tidepool.atlassian.net/browse/BACK-3839

[BACK-3839] Relax and simplify bolus validation
