config/config_test.go, data/context/standard_test.go, data/normalizer/standard_test.go, data/parser/standard_array_test.go, data/parser/standard_object_test.go, data/validator/standard_boolean_test.go, data/validator/standard_float_as_blood_glucose_value_test.go, data/validator/standard_float_test.go, data/validator/standard_integer_test.go, data/validator/standard_interface_array_test.go, data/validator/standard_interface_test.go, data/validator/standard_object_array_test.go, data/validator/standard_object_test.go, data/validator/standard_string_array_test.go, data/validator/standard_string_as_blood_glucose_units_test.go, data/validator/standard_string_as_time_test.go, data/validator/standard_string_test.go, data/validator/standard_test.go, environment/environment_test.go, log/log_test.go, userservices/client/standard_test.go, version/version_test.go
@jhbate Per you thoughts in an earlier PR. I agree, it does read better.
=> Expect(err).ToNot(HaveOccurred()) better than Expect(err).To(Succeed())

data/types/base/device/timechange/change.go, data/types/base/device/timechange/timechange_test.go
@darinkrauss updates due to fields that are redundant for the timechange event 
cc @jebeck
=> remove redundant `Timezone` and `Reasons`

data/types/base/bolus/calculator/calculator.go, data/types/base/bolus/calculator/calculator_test.go, data/types/base/device/alarm/alarm.go, data/types/base/device/alarm/alarm_test.go
Minor cleanup and additional error checking in embedded bolus in calculator.
Pull out embedded deviceEvent/status from deviceEvent/alarm, do proper validation and normalization, store reference link (id) to embedded deviceEvent/status into containing deviceEvent/alarm.
@jh-bate @gniezen `@anyone`?
=> Allow embedded deviceEvent/status in deviceEvent/alarm; cleanup calculator embedded bolus

Godeps/Godeps.json, tools/tapi/README.md, tools/tapi/api/api.go, tools/tapi/api/auth.go, tools/tapi/api/common.go, tools/tapi/api/dataset.go, tools/tapi/api/request.go, tools/tapi/api/response.go, tools/tapi/api/user.go, tools/tapi/cmd/auth.go, tools/tapi/cmd/cmd.go, tools/tapi/cmd/common.go, tools/tapi/cmd/dataset.go, tools/tapi/cmd/user.go, tools/tapi/cmd/version.go, tools/tapi/tapi.go, vendor/github.com/mitchellh/go-homedir/LICENSE, vendor/github.com/mitchellh/go-homedir/README.md, vendor/github.com/mitchellh/go-homedir/homedir.go, vendor/golang.org/x/crypto/LICENSE, vendor/golang.org/x/crypto/PATENTS, vendor/golang.org/x/crypto/ssh/terminal/terminal.go, vendor/golang.org/x/crypto/ssh/terminal/util.go, vendor/golang.org/x/crypto/ssh/terminal/util_bsd.go, vendor/golang.org/x/crypto/ssh/terminal/util_linux.go, vendor/golang.org/x/crypto/ssh/terminal/util_plan9.go, vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
@jh-bate This is the beginning of a command-line tool I started a while back. I added the "dataset list" and "dataset delete" command so that Nick can use this to test the delete uploads feature (rather than Postman, which would be quite confusing/onerous to test delete uploads with).
This is just a tool that invokes the API so there aren't any tests.
(I didn't commit a bunch of the other commands in with this tool as they aren't fully tested.)
=> Add tapi tool for command-line testing; include dataset list/delete

data/deduplicator/delegate/delegate_test.go, data/deduplicator/truncate/truncate_test.go, data/store/mongo/mongo.go, data/store/mongo/mongo_test.go, data/store/store.go, dataservices/service/api/v1/v1_suite_test.go, dataservices/service/context/standard.go, store/mongo/mongo.go, store/mongo/mongo_test.go, store/store.go, userservices/service/context/standard.go
@jh-bate The agent is the user ID that is authenticated (or empty string if server) on the request. The agent is used for all `createdUserID`, `modifiedUserID`, and `deleteUserID` fields, as appropriate.
=> Add Agent to global store session

data/deduplicator/delegate/delegate_test.go, data/deduplicator/truncate/truncate_test.go, data/store/mongo/mongo.go, data/store/mongo/mongo_test.go, data/store/store.go, dataservices/client/client.go, dataservices/client/standard.go, dataservices/client/standard_test.go, dataservices/service/api/v1/datasets_data_create.go, dataservices/service/api/v1/datasets_delete.go, dataservices/service/api/v1/datasets_delete_test.go, dataservices/service/api/v1/datasets_update.go, dataservices/service/api/v1/users_data_delete.go, dataservices/service/api/v1/users_data_delete_test.go, dataservices/service/api/v1/users_datasets_get.go, dataservices/service/api/v1/users_datasets_get_test.go, dataservices/service/api/v1/v1_suite_test.go, dataservices/service/service/standard.go, task/store/mongo/mongo.go, task/store/mongo/mongo_test.go, task/store/store.go
@jh-bate Rather than creating a separate endpoint for destroying tasks, I just piggy-backed it on to destroying data. Tasks (or data syncTasks) need to be generalized into either a "background job" mechanism or a message/event based system.
Also, for all store functions that operate on an object id, I changed the function name to have the "ByID" suffix so it is clear and consistent what the function does.
=> Destroy tasks with data; use ByID suffix for consistency/clarity

data/store/mongo/mongo.go, data/store/mongo/mongo_test.go, dataservices/service/api/v1/datasets_data_create.go, dataservices/service/api/v1/datasets_delete.go, dataservices/service/api/v1/datasets_delete_test.go, dataservices/service/api/v1/datasets_update.go, tools/tapi/cmd/common.go
@jh-bate Per our Slack conversation, all Get(Object)ByID store functions (that intend to return a single object) now return nil for the object (and no error) if the object doesn't exist.
Also, removed all usage of the `One` mgo function as it returns error if there is no object. Instead, use the `All` function with `Limit(2)` to handle 0, 1, or > 1 objects in existence. If 0, then returns nil; if 1, then returns the object; if > 1, then returns the object and warns about multiples for the same id. (In a perfect world, where we had a unique index on the object ids, this could never happen, but we aren't there yet. ;) )
=> GetDatasetByID returns nil (rather than error) if dataset not found

app/string.go, app/string_test.go, tools/tapi/api/auth.go, tools/tapi/api/user.go, tools/tapi/cmd/user.go, user/role.go, user/role_test.go, user/store/mongo/mongo_test.go, user/user.go, user/user_suite_test.go, user/user_test.go, userservices/service/api/v1/users_delete.go, userservices/service/api/v1/users_delete_test.go
@jh-bate Per discussion with Brandon and Howard, we don't want to accidentally delete a clinic account (as it would create a whole range of complicated issues). Therefore, I updated the code to prevent this. If a clinic account really needs to be deleted, then we'll have to delete all of the custodial accounts first, remove the clinic role, and then delete the account.
=> Clinic accounts should not be able to be deleted

data/store/mongo/mongo.go, dataservices/client/standard.go, log/null_test.go, message/store/mongo/mongo.go, notification/store/mongo/mongo.go, permission/store/mongo/mongo.go, profile/store/mongo/mongo.go, session/store/mongo/mongo.go, task/store/mongo/mongo.go, user/store/mongo/mongo.go, userservices/client/standard.go
@jh-bate Quick cleanup of logs for consistency. I noticed this while adding new log statements.  Use camelCase for keys since this is our JSON standard. Do not write full objects to log as it may contain user data, only write object ids.
=> Clean log statements; use camelCase for keys; only report ids, not objects

data/datum.go, data/deduplicator.go, data/deduplicator/delegate.go, data/deduplicator/factory.go, data/deduplicator/test/factory.go, data/deduplicator/truncate.go, data/deduplicator/truncate_test.go, data/store/mongo/mongo_test.go, data/test/datum.go, data/types/base/base.go, data/types/base/base_test.go, data/types/base/upload/upload.go, dataservices/service/api/v1/datasets_data_create.go, dataservices/service/api/v1/datasets_update.go
@jh-bate Rename `_dataState` to just `_state` (more accurate, plus no other field has `data` prefix though others are pertinent to data, as well.). Migration should be performed after deployment (though, not required). Move `deduplicator` descriptor as first class citizen of `data.Datum` (needed for upcoming de-duplicator work; was limited to `upload` data type).
=> Upload data type improvements

data/types/base/blood/blood.go, data/types/base/blood/blood_suite_test.go, data/types/base/blood/blood_test.go, data/types/base/blood/glucose/continuous/continuous.go, data/types/base/blood/glucose/continuous/continuous_suite_test.go, data/types/base/blood/glucose/continuous/continuous_test.go, data/types/base/blood/glucose/glucose.go, data/types/base/blood/glucose/glucose_suite_test.go, data/types/base/blood/glucose/glucose_test.go, data/types/base/blood/glucose/selfmonitored/selfmonitored.go, data/types/base/blood/glucose/selfmonitored/selfmonitored_test.go, data/types/base/blood/ketone/ketone.go, data/types/base/blood/ketone/ketone_suite_test.go, data/types/base/blood/ketone/ketone_test.go, data/types/base/settings/pump/pump.go, data/types/base/settings/pump/pump_suite_test.go
@jh-bate Main refactor that previous PRs lead to. Create data type hierarchy of `blood` -> `ketone` and `blood` -> `glucose` -> `continuous`/`selfmonitored` to allow sharing of common functionality and tests. Full tests for entire hierarchy. Also missed a type rename for pump settings.
=> Refactor out common blood glucose/ketone; tests

data/blood/glucose/glucose.go, data/blood/glucose/glucose_test.go, data/blood/glucose/target_test.go, data/types/base/blood/glucose/glucose_test.go, data/types/base/bolus/calculator/calculator_test.go, data/types/base/device/calibration/calibration_test.go, data/types/base/settings/pump/pump_test.go
=> Keep 5 decimal places on converting mg/dL to mmol/L (to do otherwise implies greater accuracy than is available)

data/types/base/settings/pump/pump.go
@jh-bate Fix pump data type functions to use `p` struct variable name (not `s`).
=> Fix struct function instance variable name

data/datum.go, data/test/datum.go, data/types/base/basal/basal.go, data/types/base/base.go, data/types/base/base_test.go, data/types/base/blood/blood.go, data/types/base/blood/blood_test.go, data/types/base/bolus/bolus.go, data/types/base/bolus/bolus_test.go, data/types/base/device/device.go, data/types/base/device/device_test.go
@jh-bate The identity fields are the values for each data that are used to generate a unique hash for de-duplication. These are similar to `jellyfish`, but order is slightly different and one or two additional fields for ensuring uniqueness. Add full tests for `bolus` and `device` data.
=> Add data identity fields to be used by hash generation for de-duplication

data/deduplicator/delegate_test.go, data/deduplicator/test/factory.go, data/deduplicator/truncate_test.go, data/factory/standard_test.go, data/normalizer/standard_test.go, data/parser/parser_test.go, data/parser/standard_array_test.go, data/parser/standard_object_test.go, data/store/test/session.go, data/test/datum.go, data/test/deduplicator.go, dataservices/service/api/v1/v1_suite_test.go
@jh-bate By creating and using explicit New* functions for test mocks, we can add a unique identifier to each test mock for comparison purposes (implicitly used by the Gomega Equals/ConsistsOf matchers).
=> Add functions to generate unique test data

tools/migrate_pmid_to_uid/README.md, tools/migrate_pmid_to_uid/migrate_pmid_to_uid.go
@jh-bate This script migrates the Seagull metadata database from using the `_id` (private.meta.id) to `userId` as its primary key. It would run before (and after to ensure everything was converted) deploying the next version of Seagull.
=> Add migrate_pmid_to_uid tool (for Seagull metadata migration)

data/deduplicator.go, data/deduplicator/base.go, data/deduplicator/base_test.go, data/deduplicator/hash_deactivate_old.go, data/deduplicator/truncate.go, data/deduplicator_test.go, data/test/deduplicator.go
@jh-bate Moving towards a "org.tidepool.X" naming scheme throughout. Add versioning to allow greater flexibility in data mining and implementation.
=> Add deduplicator version; update deduplicator name scheme

tools/migrate_data_deduplicator_descriptor/migrate_data_deduplicator_descriptor.go
@jh-bate I realized I forgot to create a migration script for the code just merged into master, namely tag `v1.8.0`. This is that migration. I will update subsequent PRs to evolve this migration to the current standard.
=> Migration for data deduplicator descriptor name and version

CHANGELOG.md, data/deduplicator.go, data/deduplicator/hash_deactivate_old.go, data/deduplicator/hash_deactivate_old_test.go, data/store/mongo/mongo.go, data/store/mongo/mongo_test.go, data/store/store.go, data/store/test/session.go, data/types/base.go
@jh-bate Add `archivedTime` and `archivedDatasetId` field to all data records. Allows exact history of deduplication with multiple uploads that can be unrolled. Allows fully accurate deduplication and upload deletion. Key changes are in the mongo queries. Upload deduplication is still fast with the same two queries (with a couple extra fields on update, but that doesn't affect performance). Upload deletion is now a couple more database calls, but still reasonable performance with latest indexes. (Also, upload deletion performance isn't that important.)
=> Add data archive fields; revamp Mongo queries for consistent deduplication and delete for Medtronic

CHANGELOG.md, crypto/crypto.go, data/deduplicator.go, data/deduplicator/hash_deactivate_old.go, data/deduplicator/hash_deactivate_old_test.go, data/store/mongo/mongo.go, data/store/mongo/mongo_test.go, data/store/store.go, data/store/test/session.go, data/types/base.go, dataservices/service/service/standard.go, service/api/standard.go, service/middleware/header.go, service/middleware/header_test.go, service/middleware/trace.go, userservices/client/standard.go, userservices/service/service/standard.go
@jh-bate Needed this for debugging a problem on production recently. Adding it so we have it in the future. The authentication token (X-Tidepool-Session-Token header value) is MD5 hashed first before adding to the log to 1) prevent unnecessary exposure of session tokens; and 2) shrink the size of the value added to the log. This means that you need to run the session token through an MD5 hasher before searching the logs.
=> Add header middleware; add MD5 hash of authentication token to log

.golintignore, dataservices/service/api/status.go, dataservices/service/api/v1/time_get.go, dataservices/service/api/v1/time_get_test.go, dataservices/service/api/v1/v1.go, dataservices/service/api/version.go, service/context/standard.go, service/response.go, service/response_test.go, userservices/service/api/status.go, userservices/service/api/version.go
@jh-bate @gniezen What it says on the tin. This will be used by the uploader to verify that a device is set to the correct time before uploading. (We cannot reasonably rely on the computer time as it may be incorrect.)
=> Add time API; return Date header with all responses

CHANGELOG.md, config/config.go, config/env/reporter.go, config/env/reporter_test.go, config/test/reporter.go, dataservices/client/config.go, log/config.go, metricservices/client/config.go, permission/store/mongo/config.go, service/server/config.go, store/mongo/config.go, user/store/mongo/config.go, userservices/client/config.go
@jh-bate Rename `String` to `Get` and `StringOrDefault` to `GetWithDefault` so that we can later (next commit/PR) add a `Set` and `Delete` function. Much more readable this way, too. For example, `config.Get("address")`.
=> Rename config String to Get and StringOrDefault to GetWithDefault

CHANGELOG.md, config/config.go, config/env/reporter.go, config/env/reporter_test.go, config/test/reporter.go
@jh-bate Add aforementioned `Set` and `Delete` to config. Allows for overriding configuration from command line applications (later commit/PR).
=> Add ability to set and delete to config

CHANGELOG.md, Makefile, application/application.go, application/application_test.go, application/version/reporter.go, application/version/reporter_test.go, application/version/test/init.go, application/version/version_suite_test.go, service/service_test.go, tool/mongo/tool_test.go, tool/tool_test.go, tools/tapi/cmd/cmd.go, version/reporter.go, version/reporter_test.go, version/version.go
@jh-bate Relatively minor refactor to move specific incarnation of `VersionReporter` into `application` package (since it is directly tied to the application, after all). Also add a test file that can be included to automatically initialize the default version parameters (normally these are set via the Makefile during builds, but cannot be set during testing via `ginkgo`).
=> Refactor version package to align with new application package

dexcom/fetch/translate.go
@jh-bate Fix incorrect calculation for determining UTC time of each Dexcom API datum.
=> Use actual system time rather than calculated

dexcom/fetch/runner.go, page/pagination_test.go, request/parser.go, request/values_parser.go, structure/normalizer/normalizer.go, structure/parser/array_parser.go, structure/parser/object_parser.go, structure/validator/validator.go
@jh-bate By adding a default source for structure functionality then we can capture, by default, the most information about what structures fields fail validation, parsing, or normalization.  (Not as "perfect" as specifying the source at the time of processing, but this is much more pragmatic. Almost all will use the default and only structures parsed out of the request query will use a specific non-default source.)
=> Add default source for structure validator, parser, and normalizer

dexcom/fetch/runner.go
@jh-bate Quick, but important, one.
=> Run Dexcom fetch task every 45 to 75 minutes (rather than always 1 hour)

CHANGELOG.md, auth/service/api/v1/oauth.go, dexcom/calibration.go, dexcom/device.go, dexcom/dexcom.go, dexcom/egv.go, dexcom/event.go, dexcom/fetch/runner.go, oauth/token/source.go
@jh-bate We'll only use this after getting positive confirmation from Dexcom that this legacy code is no longer necessary.
=> Remove legacy code to fixup unexpected data from Dexcom API

CHANGELOG.md, auth/client/external.go, client/config.go, config/config.go, config/env/reporter.go, config/env/reporter_test.go, config/errors.go, config/errors_test.go, config/test/reporter.go, platform/config.go, service/server/config.go, store/mongo/config.go, task/queue/queue.go
@jh-bate Need to switch to returning error if config value not found, rather than a simple bool for more normal Golang functionality.
=> Return error from config.Get rather than bool for compatibility

CHANGELOG.md, auth/service/api/v1/oauth.go, dexcom/client/client.go, dexcom/fetch/runner.go, dexcom/provider/provider.go, oauth/client/client.go, oauth/oauth.go, oauth/provider/provider.go, oauth/token/source.go
@jh-bate Cleanup of oauth package to be more friendly to other grant types. Next commit adds the client credentials grant, which will be used by the Auth0 management tool.
=> Refactor oauth package to allow alternate grant workflows

CHANGELOG.md, structure/validator.go, structure/validator/array.go, structure/validator/array_test.go, structure/validator/object.go, structure/validator/object_test.go, structure/validator/validator.go, structure/validator/validator_test.go
@jh-bate More useful structure validators for Objects (map[string]interface{}) and Arrays ([]interface{}).
=> Add Object and Array structure validators

CHANGELOG.md, Makefile
@jh-bate This works pretty much the same as `make test-watch` where the tests are automatically run if it detects any file changes. These two targets just do `build` or `ci-build` if any files change. Works well when writing code to quickly get rid of syntax errors and the like.
=> Add build-watch and ci-build-watch targets to automatic build after file change

CHANGELOG.md, data/factory/standard.go, data/factory/standard_test.go, data/types/basal/automated/automated.go, data/types/basal/automated/automated_suite_test.go, data/types/basal/automated/automated_test.go, data/types/basal/automated/test/automated.go, data/types/basal/suspend/suspend.go, data/types/basal/suspend/suspend_test.go, data/types/basal/temporary/temporary_test.go
@jh-bate Add new `basal/automated` type. Very much like `basal/scheduled`, but cannot be suppressed by a `basal/temp` (only by a `basal/suspend`).
=> Add automated basal data type

CHANGELOG.md, dexcom/fetch/runner.go, oauth/token/source.go, task/queue/queue.go
@pazaan Update the provider session (the OAuth tokens) and return any error *before* checking for any error from the actual Dexcom API. This covers the case where the access token is refreshed successfully, but the subsequent API call (to get devices, egvs, etc) fails (for whatever reason, including expected data). The access token will now be correctly stored in the database after *any* successful token refresh.
Also, log any error (transient or not) that occurs when running the task.
=> Fix Dexcom API authentication failure; always update provider session, even if error

CHANGELOG.md, dexcom/device.go, dexcom/dexcom.go, dexcom/fetch/runner.go
@pazaan Allow "Unknown" as a Dexcom device model. Unfortunately, we need to support this. I also note that this comes down from HealthKit via Tidepool Mobile, as well.
=> Fix Dexcom API unknown device model failure; allow unknown device model

CHANGELOG.md, data/types/insulin/dose.go, data/types/insulin/dose_test.go, dexcom/device.go, dexcom/event.go, dexcom/fetch/runner.go
@pazaan Fixes all of the (currently known) unexpected data from the Dexcom API. In some cases it is due to unclear/incomplete documentation. In other cases it directly contradicts the documentation. In any case we have to (temporarily, in some cases) fix it out our end so we end up with valid data and a working Dexcom connection. The turnaround time for getting it fixed at the source is lengthy.
I expect that we will see some additional unexpected data failures since the authentication failure (jn previous PR) was taking precedence over these types of failures.
=> Fix Dexcom API unexpected data; temporarily modify incoming data to expected values

.golintignore, CHANGELOG.md, data/datum.go, data/types/basal/factory/factory.go, data/types/basal/factory/factory_suite_test.go, data/types/basal/factory/factory_test.go, data/types/bolus/factory/factory.go, data/types/bolus/factory/factory_suite_test.go, data/types/bolus/factory/factory_test.go, data/types/calculator/calculator.go, data/types/calculator/calculator_test.go, data/types/device/alarm/alarm.go, data/types/device/alarm/alarm_test.go, data/types/device/factory/factory.go, data/types/device/factory/factory_suite_test.go, data/types/device/factory/factory_test.go, data/types/device/reservoirchange/reservoirchange.go, data/types/device/reservoirchange/reservoirchange_test.go, data/types/device/status/status.go, data/types/device/status/status_test.go, data/types/factory/factory.go, data/types/factory/factory_suite_test.go, data/types/factory/factory_test.go
@jh-bate The old data factory used to be entirely away from the `data/types` package hierarchy which meant that you couldn't use parts within the `data/types` package hierarchy (due to circular dependencies).  
Broke this up into a factory for each type, sub type, and delivery type *into a `factory` package under the relevant `data/types` package*. This allows you to use factories from other data types. For example, the `calculator` type can now use the `basal` type factory.
Also, the factories are simpler to understand. None of the map of func map funcs garbage, which, while perhaps clever, was not really understandable. (Understandable > clever).
(Note: Still avoiding "parsing" tests until I can get the new structure parser installed so I don't have to rewrite a whole bunch of code.)
=> Refactor data factory into specific packages

CHANGELOG.md, data/types/common/location/gps.go, data/types/common/location/gps_test.go, data/types/common/location/test/gps.go
@jh-bate The location common field type can have an origin (which device generated the GPS data) that differs from the device generating the diabetes data.
=> Add origin to location common data type

CHANGELOG.md, data/types/insulin/concentration.go, data/types/insulin/concentration_test.go, data/types/insulin/dose.go, data/types/insulin/dose_test.go, data/types/settings/pump/basal_rate_maximum.go, data/types/settings/pump/basal_rate_maximum_test.go, data/types/settings/pump/basal_temporary.go, data/types/settings/pump/basal_temporary_test.go, data/types/settings/pump/bolus_amount_maximum.go, data/types/settings/pump/bolus_amount_maximum_test.go
@jh-bate Apparently, the agreed upon units of insulin is "Units", not "units". So, conforming to accepted standard, per request from Howard.
=> Use "Units" rather than "units" for insulin

CHANGELOG.md, data/types/device/status/status.go, data/types/device/status/status_test.go, data/types/device/status/test/status.go
@jh-bate Add `expectedDuration` to `deviceEvent/status` data model. Missed the first go around.
=> Add expected duration to status device event data model

CHANGELOG.md, data/types/food/food.go, data/types/food/food_test.go, data/types/food/ingredient.go, data/types/food/ingredient_test.go
@jh-bate Add ingredients (consider it a sub-array of foods so that a user can describe a whole meal in components rather than just as a sum total whole). Add `code` field for UPC code (or a variety of other coding systems).
=> Add ingredients to food data model for greater flexibility

CHANGELOG.md, application/application.go, auth/restricted_token.go, data/data_source.go, data/service/api/v1/time.go, dexcom/client/client.go, dexcom/fetch/runner.go, dexcom/fetch/translate.go, oauth/oauth.go, service/response.go
* Do not strip original time zone information using time.UTC()
* Only convert to UTC when required (eg. time.Format that requires UTC time with or without time zone)
@jh-bate
=> Fix UTC time usage

CHANGELOG.md, dexcom/device.go, dexcom/device_test.go, dexcom/dexcom.go, dexcom/dexcom_test.go, dexcom/test/alert_setting.go
@jh-bate Dexcom API is erroneously sending duplicate alert settings per device (eg. two `low` alert settings at the same time). Remove all older duplicates based upon `systemTime` field. Predicated a refactoring of the alert settings validation and related code.
=> Remove duplicate Dexcom device alert settings

CHANGELOG.md, request/request.go, request/request_test.go, request/responder.go, service/api/api.go, service/middleware/access_log.go, service/middleware/error.go, service/middleware/error_test.go
@jh-bate Add context to store any request errors and log those errors out when logging request access log entry.
=> Log any error with request

.golintignore, CHANGELOG.md, data/data_set.go, data/service/api/v1/data_set.go, dexcom/fetch/runner.go
@jh-bate Just use pointers for the fields of the data set structure. Not sure why I originally had these as non-pointers, but I decided (a while back) that use of pointers for almost all fields in any JSON serialized structs made the most sense.
=> Use pointers for data set fields to match upload fields

.golintignore, CHANGELOG.md, data/data_set.go, data/service/api/v1/users_datasets_create.go, data/storeDEPRECATED/mongo/mongo.go, data/types/base.go, data/types/base_test.go, data/types/upload/upload.go, data/types/upload/upload_test.go
@jh-bate Tidepool Mobile is switching over to use a single, continuous data set for all data (rather than hundreds to thousands over a long period of time). Also, Tidepool Mobile will be adding a number of new data types. Thus, some of the previously required fields are now optional. Also, allow data set query to filter on client name (so that Tidepool Mobile can find its one data set).
=> Enable new continuous Tidepool Mobile data set

CHANGELOG.md, blob/client/client.go, blob/client/client_test.go, blob/service/api/v1/v1.go, blob/service/api/v1/v1_test.go, blob/service/client.go, blob/service/client_test.go, blob/store/structured/mongo/mongo.go, blob/store/structured/mongo/mongo_test.go, blob/test/blob.go
@jh-bate Simple variable name renames in order to make it more amenable as a template service.
=> Rename various to more generic form in blob service

CHANGELOG.md, request/condition.go, request/condition_test.go, request/errors.go, request/errors_test.go, request/test/condition.go, store/structured/mongo/mongo.go, store/structured/mongo/mongo_test.go
@jh-bate The request condition (specifically the revision) can be used to prevent two separate process from updating the same resource at the same time. See next PRs for details.
=> Add request condition revision to enforce specific update and delete operations

CHANGELOG.md, data/service/api/v1/data_source.go, data/source/client/client.go, data/source/client/client_test.go, data/source/service/client/client.go, data/source/service/client/client_test.go, data/source/source.go, data/source/source_test.go, data/source/store/structured/mongo/mongo.go, data/source/store/structured/mongo/mongo_test.go, data/source/store/structured/test/session.go, data/source/test/client.go, data/source/test/source.go, dexcom/fetch/runner.go, dexcom/provider/provider.go
@jh-bate Enable the capability to only update/delete a resource if it is at an expected revision. This can prevent two services from modifying the same resource at the same time resulting in potential data loss.
=> Add data source revision

CHANGELOG.md, blob/blob.go, blob/blob_test.go, blob/client/client.go, blob/client/client_test.go, blob/service/api/v1/v1.go, blob/service/api/v1/v1_test.go, blob/service/client/client.go, blob/service/client/client_test.go, blob/store/structured/mongo/mongo.go, blob/store/structured/mongo/mongo_test.go, blob/store/structured/structured.go, blob/store/structured/test/session.go, blob/test/blob.go, blob/test/client.go
@jh-bate Enable the capability to only update/delete a resource if it is at an expected revision. This can prevent two services from modifying the same resource at the same time resulting in potential data loss.
=> Add blob revision

CHANGELOG.md, data/deduplicator.go, data/deduplicator/continuous_origin.go, data/deduplicator/continuous_origin_test.go, data/deduplicator/delegate.go, data/deduplicator/delegate_test.go, data/service/service/standard.go, data/storeDEPRECATED/mongo/mongo.go, data/storeDEPRECATED/mongo/mongo_suite_test.go, data/storeDEPRECATED/mongo/mongo_test.go, data/storeDEPRECATED/store.go, data/storeDEPRECATED/test/data_session.go, data/types/upload/upload.go
* Add continuous origin deduplicator to use origin id as deduplication key for continuous data sets
* Allow client to specific data set deduplicator
@jh-bate Will be used by v2 Dexcom API and updates to Tidepool Mobile. Deduplicates within the same continuous data set, but uses the new origin.id field as the deduplication key.
=> Add continuous origin deduplicator

CHANGELOG.md, data/types/base.go, data/types/base_test.go
@jh-bate For most HealthKit data we don't have a logical device id, so make it optional rather than using some arbitrarily constructed surrogate.
=> Make device id optional for data

CHANGELOG.md, data/deduplicator/deduplicator/base.go, data/deduplicator/deduplicator/base_test.go, data/deduplicator/deduplicator/data_set_delete_origin.go, data/deduplicator/deduplicator/data_set_delete_origin_test.go, data/deduplicator/deduplicator/device_deactivate_hash_test.go, data/deduplicator/deduplicator/device_truncate_data_set_test.go, data/deduplicator/deduplicator/none_test.go, data/deduplicator/factory/factory_test.go, data/storeDEPRECATED/mongo/mongo.go, data/storeDEPRECATED/mongo/mongo_test.go, data/storeDEPRECATED/store.go, data/storeDEPRECATED/test/data_session.go, data/test/data.go, data/test/data_set.go
* Update delete data set origin deduplicator to delete duplicates found when adding data
* Update delete data set origin deduplicator to deactivate deleted data
* Update base deduplicator to activate data set separately from data set data
* Update data store to not activate data set when data set data activated
* Add data selectors to data set data operations to target specific data records
* Update data store to add activate, archive, delete, destroy deleted, and destroy operations on data set data
* Refactor data store and test for code consistency
@jh-bate
=> Update data deduplicators to accommodate deactivating deleted data

CHANGELOG.md, data/data.go, data/data_test.go
@pazaan Same as already approved PR https://github.com/tidepool-org/platform/pull/384. Moving to a `develop` branch so created a new PR to keep it clean.
=> Fix data set id validation to allow Jellyfish id format

CHANGELOG.md, blob/blob.go, blob/blob_test.go, blob/client/client.go, blob/client/client_test.go, blob/service/api/v1/v1.go, blob/service/api/v1/v1_test.go, blob/service/client/client.go, blob/service/client/client_test.go, blob/test/blob.go, blob/test/client.go, client/client.go, client/client_test.go, config/test/reporter.go, profile/store/mongo/mongo_test.go, request/errors.go, request/errors_test.go, service/test/service.go
* Return HTTP status code 413 Request Entity Too Large when blob size exceeds maximum
* Replace blob.Create with blob.Content
* Remove blob Content-Length header usage and blob.Content.Size as it does not work with content encoding
* Update test config reporter for better debugging
=> Fix blob size verification and handling

CHANGELOG.md, data/types/insulin/dose.go, data/types/insulin/dose_test.go, data/types/insulin/test/dose.go, dexcom/alert.go, dexcom/alert_test.go, dexcom/calibration.go, dexcom/calibration_test.go, dexcom/egv.go, dexcom/egv_test.go, dexcom/event.go, dexcom/event_test.go, dexcom/fetch/translate.go, dexcom/test/alert.go
* Relax Dexcom API validations to match Tidepool data model validations
* Rename insulin dose constants to properly include units
@cbwebdevelopment Since Lenny is away and you've expressed an interest in the backend, would you mind reviewing this? Don't worry, Lenny already reviewed the counterpart PR for this branch into `master` in https://github.com/tidepool-org/platform/pull/391. Thanks!
=> Relax Dexcom API validations to match Tidepool data model validations

README.md
The README referred to a make target that does not exist.
@darinkrauss I am not certain that this is correct, but I think it is.  Please let me know.
=> Corrected README for building go tools

service/middleware/access_log.go
This is to suppress some of the noisy logging messages.
=> Quiet logging

tools/tapi/README.md, tools/tapi/cmd/cmd.go, tools/tapi/cmd/common.go, tools/tapi/cmd/user.go
@tjotala Adding `update-password` functionality to the `tapi` tool (replacing the `tidepool-pwreset.js` tool).
The corresponding `develop` PR is [available here](https://github.com/tidepool-org/platform/pull/447)
=> Add `update-password` command to `tapi`

Dockerfile.tools
Since `production` uses `alpine:latest`, we need to add alpine v3.6
repository details to be able to install `mongodb`
=> Fix installation of `mongodb` in `production` image

dexcom/egv.go, request/values_parser.go, structure/parser.go, structure/parser/object_parser.go, structure/parser/object_parser_test.go
Adds a "Forgiving Time" parser to mitigate the recently introduced
bug in the Dexcom API
* Fixes [BACK-1161]
=> BACK-1161 Mitigate Dexcom API bug

origin/origin.go, origin/origin_test.go
This adds the ability to specify that the origin for a datum is an application (not device, service, or manually entered), specifically Tidepool Loop.
Feel free to merge into your branch if you approve of the change. Thanks!
=> Add application origin type and tests

dexcom/event.go, dexcom/event_test.go
A patient reported that their data could not be synced. During the investigation I found occurrences of a validation error, where we expect a health event value to not be present, where now it's being returned as 0 
It looks like Dexcom introduced a change on their side which trips up our validation logic. The response is valid according to their API docs. I added 0 to the allowed values, because [we're ignoring](https://github.com/tidepool-org/platform/blob/8ba106f739f1337299539c2e50e9840e8266c14f/dexcom/fetch/translate.go#L451) this value anyway.
This affects 162 people and prevents us from syncing their data.
=> [BACK-1339] Fix dexcom health event validation

.travis.yml, Makefile
- Enabled go build cache, which caches build outputs for reuse in future builds. 
- Set the number of ginkgo concurrent compilers to 2 (the number of cores available to us), because the default is the number of CPUs reported by Travis is the number of host CPUs (32)
This will saves us another 2-3 minutes. The build time is now down to under 12 minutes.
=> Travis build optimizations

confirmation/store/mongo/store.go, data/storeDEPRECATED/mongo/mongo.go, user/store/structured/mongo/mongo.go, user/store/structured/mongo/mongo_test.go
An index for `users.userid` was being created in both `shoreline` and
`platform/users`, tying changes tightly together.
Remove index creation from `platform`, and leaving it to `shoreline`.
Also add comments for other places where multiple services create
indexes for the same collections.
* Fixes BACK-1437
=> [BACK-1437] Remove duplication of index creation

prescription/api/router.go, prescription/api/v1.go, prescription/api/v1_test.go, user/client/client.go, user/service/client/client.go, user/service/client/client_test.go
- Added a new admin endpoint `/v1/users/:userId/prescriptions` for retrieving prescriptions for a given user (clinician or patient)
- Added tests for api layer authorization
=> [BACK-1468] Add admin APIs for prescription service

migrations/back-1572/JellyfishHasher.go, migrations/back-1572/back-1572.go
Although [BACK-1379] fixed the `deviceId` field with additional
apostrophes in Omnipod data, it did not migrate the `id` and `_id`
fields, which are required for correct deduplication and/or archival.
Since the `deviceId` field has already had the apostrophes removed,
this new migration script finds duplicates by generating the expected
hash and comparing it against Mongo, and either fixes data or archives
duplicates accordingly.
* Fixes [BACK-1572]
[BACK-1379]: https://tidepool.atlassian.net/browse/BACK-1379
[BACK-1572]: https://tidepool.atlassian.net/browse/BACK-1572
=> [BACK-1572] Migrate or archive duplicate `jellyfish` Omnipod data

tool/mongo/tool.go
`Tool` did not previously parse the Mongo Scheme, Timeout or OptParams
from the environment, meaning that migrations could not connect to AtlasDB
* Fixes [BACK-1572]
[BACK-1572]: https://tidepool.atlassian.net/browse/BACK-1572
=> [BACK-1572] Fix Mongo ENV parsing

migrations/back-393/back-393.go, prescription/prescription_test.go
This adds the `sharerId` field to existing gatekeeper.perms documents.
=> Added migration for back-393

migrations/back-1572/JellyfishHasher.go
The ObjectIDHash was previously generated by the `id` present in the data,
but it should have been generated based on what the `id` _should_ be.
* Fixes [BACK-1572]
[BACK-1572]: https://tidepool.atlassian.net/browse/BACK-1572
=> [BACK-1572] Generate ObjectIDHash based on the correct IDHash

Dockerfile.tools
Production image wasn't building correctly due to a line continuation
that wasn't removed.
=> Fix bug introduced in last Dockerfile.tools change

prescription/revision.go, prescription/store/mongo/prescription_repository_test.go
When prescription are updated we're using the mongo `$set` operator that doesn't allow un-setting fields when it's used along with `omitempty` bson struct tag. This caused `latestRevision` attribute to be populated by the merged object of latestRevision + non-empty updated fields.
This bug causes intermittent unit test failures in the `master` branch.
=> Allow un-setting prescription settings

service/api/api.go
Tapani asked me to cut back on the sumo logging.  This is a major source.  It is redundant since we are doing access logging with Gloo.
=> Turn off platform access logging

service/api/api.go, service/middleware/access_log.go, service/middleware/access_log_test.go
https://github.com/tidepool-org/platform/pull/529 completely disabled error logging. This re-enabled access logging only if the request results in an error.
=> Enable error logging

data/store/mongo/mongo.go, data/store/mongo/mongo_test.go
The deployment of the data service failed on prod, because the index was created using the atlas ui, which spits out partial filter expression options in a random order
I deleted the indexes on all non-prod environments and let the application create them so they match prod
=> Fix order of elements in index options

user/store/structured/mongo/mongo.go, user/store/structured/mongo/mongo_test.go, user/test/user.go, user/user.go, user/user_test.go
Now that the user service has been deprecated and it's not in use, we forward all requests to `/v1/users` to shoreline. However, shoreline responses contain extra fields that make the user object parser fail.
The user client is currently only used by the prescription service which is not in production. Its use will be replaced by external auth + clinic service client, so this temporary fix will never make it to production.
=> Add temporary fix for incomplete user parsing

errors/errors.go, errors/errors_test.go, errors/test/errors.go, store/structured/mongo/config_test.go, task/store/mongo/mongo_test.go
Faulty serailization of errors affects the task service, because we serialize failures in the task document. When multiple errors occur during a sync, we can't serialize/desiarilize documents correctly, because of change of the interfaces provided by the official mongo driver.
Serialized errors are polymorphic and can be documents (when the type is `object`), arrays (when the type is `array`) or strings (when the std lib error is used). `mgo` supported marshalling and unmarshalling through a single interface, but this is now illegal with the official mongo driver. `MarshalBSON` and `UnmarshalBSON` should only be used on types that can be serialized as top-level documents - this is not the case for strings and arrays.
The right way to do this is to use `MarshalBSONValue` and …
=> [BACK-1779] Use bson value codec for errors

prescription/access_code.go, prescription/access_code_test.go
Darin noticed that we allow "1" in the prescription access code, while disallowing "I", "0", and "O". For symmetry with "0" and "O" and to avoid input mistakes, we should disallow "1" as well.
=> [BACK-1927] Disallow "1" in access code

data/store/mongo/mongo.go, data/store/mongo/mongo_test.go
This will allows to restore the data service in a working state faster, by leveraging the index created on the primary, before secondaries have completed building the indexes and without having to drop the old (corrupted index).
It looks like Jellyfish and tide-whisperer do not make use of this index.
=> [IN-29] Add temporary index hint for the newly created unique upload id index

structure/parser/object_parser.go
The object parser returns errors if there are unparsed field in an object. This causes unexpected errors every time a new field is added from a third-party provider even if their change is backward compatible. For this reason I believe it's better if we don't default to this.
Dexcom added a new field to their responses which is undocumented, thus not parsed by us. This resulted in sync failures for all tasks in the last ~20h.
=> Do not return a validation errors if there are unparsed fields

data/types/bolus/combination/combination.go, data/types/bolus/combination/combination_test.go
Now the `bolus/combination` validator allows both `extended` and `normal` to be zero if either `expectedNormal` or `expectedExtended` are larger than 0.
=> [BACK-1914] Fix combo boluses for 600 Series Medtronic Pumps

Dockerfile.tools
Newer version of mongo are not available for alpine. We might need to switch to a different image.
=> Use mongo 4.0 in the tools image

prescription/revision.go
I will manually update the attributes of existing prescriptions
=> [BACK-1932] Fix typo in prescription document attribute

dexcom/device.go, dexcom/device_test.go
This adds "g6 pro" to the list of supported Dexcom CGM devices, so that data from those devices can be imported via Dexcom Clarity.
=> [BACK-2029] Add Dexcom G6 Pro to the list of devices we can import through Dexcom Clarity

data/client/client.go, data/service/service/client.go, data/store/mongo/mongo_data.go, data/store/mongo/mongo_summary.go, data/store/mongo/mongo_test.go, data/store/store.go, data/summary/summary.go, data/summary/summary_test.go
Current sticking points fixed by this PR:
1. varying precision of date strings from different data sources can result in "past" data being pulled into a query due to db string comparison
2. backfill checks summary table first, resulting in unique key errors if a user uploads new data in the lengthy gap between the distinct summary query and insert, as getting distinct deviceData cgm users takes significant time.
3. summary will calculate far-future data, resulting in data which can be made to not match tidepool web
=> Summary service tuning for live data

data/service/service/client.go, data/store/mongo/mongo_summary.go, data/store/mongo/mongo_test.go
Stop GetSummary from returning a 500 error when it should be returning 404 for summary not found
=> Fix GetSummary returning 500 instead of 404

data/service/service/client.go
when calling updatesummary with no new data (either during a full scan, or a mismark, or if the data is deleted before calculation), LastUpdatedDate will become zero as it is improperly set.
=> LastUpdatedDate wrongly Zero if UpdateSummary called unusually

task/queue/queue.go, task/store/mongo/mongo.go, task/store/mongo/mongo_test.go, task/task.go
Multiple workers can currently claim a single task and run it at the same time, this should fix that.
=> Fix task claim race condition

auth/service/api/v1/oauth.go, dexcom/client/client.go, dexcom/device.go, dexcom/fetch/runner.go
See [BACK-2339]
- Oauth redirect no longer returns early with error message if a user has a previous mathcing provider session.  This was preventing reconnection requests from the clinic to complete.  Now, the current data source is put into a `disconnected` state, and the current associated `task` and `provider_session` are replaced with new ones.  The method called here to do this is the same one that gets called if a patient clicks 'Disconnect' and then reconnects from their profile page, which was the current way we handle reconnection needs (this of course can't be done in the case of custodial users, which is why this is needed)
- Added a check on the dexcom client address to determine if we're accessing sandbox data, and updating the paths accordingly when that is the case.  Also, …
=> [BACK-2339] Replace existing with new provider session in oauth redirect

appvalidate/appvalidate.go, appvalidate/assertion.go, appvalidate/attestation.go, appvalidate/base64.go, appvalidate/validator.go, auth/service/api/v1/appvalidate.go, auth/service/api/v1/appvalidate_test.go, vendor/github.com/bas-d/appattest/assertion/assertion.go, vendor/modules.txt
This commit adds app assertion verification. The user can get an assertion verified only after being attested and only after generating an assertion challenge. Once the assertion is verified, the user will be granted access to some private or sensitive information.
=> [BACK-2165] Add app assertion verification route.

dexcom/alert.go, dexcom/alert_test.go, dexcom/dexcom.go, dexcom/dexcom_test.go
https://tidepool.atlassian.net/browse/BACK-2328
- remove validation for dexcom device ID if its not sent
- allow AlertSchedules to be empty
- remove dead code
=> [BACK-2328] dexcom validation updates

dexcom/alert.go, dexcom/alert_test.go
validation was failing with times such as `8:00 AM` and `9:00 PM` being sent
- allow for existing 24hr format
- including 12hr format (am or pm)
- ignore case and allow `am` or `AM` or `aM`
- allow extra spacing between time and postfix  `8:00 AM` or `8:00   AM`
=> BACK-2328 allow for 12hr time format

Dockerfile.tools, tools/ashrc
Since we also need to move to mongodb 6.x, and the clientside mongosh tools will work fine against older versions, this commit moves us to 6.x, instead of just the latest 4.x.
=> Update tools container to fix build failures

.travis.yml, data/store/mongo/mongo.go, data/store/mongo/mongo_data.go, data/store/mongo/mongo_data_set.go, data/store/mongo/mongo_datum.go, data/store/mongo/mongo_test.go, data/store/store.go, tools/benchmark_data_store/benchmark_data_store.go
Move deviceData with type='upload' to its own collection named deviceDataSets
which acts as a collection for "parent" datum where its children are in the original deviceData collection. Split platform/data/store.DataRepository into 2 repositories, one for DataSet and one for data of these DataSets called DataSetRepository and DatumRepository, respectively.
=> [BACK-1758] Move data with type=upload to its own collection with dual read/writes.

data/store/mongo/mongo_data.go, data/store/mongo/mongo_test.go
Handle out of bounds during dataSets retrieval when merging dataSets from both deviceData and deviceDataSets collections due to using improper slice counter/index.
=> Handle out of bounds during dataSets retrieval 

data/store/mongo/mongo_data.go, data/store/mongo/mongo_data_set.go, data/store/mongo/mongo_datum.go, data/store/mongo/mongo_test.go
This commit removes dual reading and writing from the deviceDataSets and deviceData collection and instead does a single collection read and write for datum (colleciton deviceData) and uploads (collection deviceDataSets). This is intended to be done AFTER migration of all type="upload" from the deviceData to the deviceDataSets collection.
=> [BACK-1758] Single separate writes to deviceData and deviceDataSets collections.

README.md
Specifically, that they're typically run on the k8s cluster that's setup via the development repo.
=> README.md: adds a note about running services locally

.github/workflows/main.yml
see https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDISINTEGRATIONIMAGING-5880692
in an effort to keep the build clean (or before we potential remove the imaging service) this ignores the above issue for now ... well for the next 6 mths anyway
=> SNYK ignore known issue for 6 months

data/store/mongo/mongo_summary.go, data/store/mongo/mongo_test.go, data/summary/summary.go, task/summary/migrationrunner.go
Adjusts indexes to better match summary queries
Also fixes the processing loop that occurs when a summary is being migrated, but user has no active data within the last 2 years.
=> Tide-v1 release bugfixes

store/structured/mongo/mongo_test.go
A pair of tests were testing error paths for non-responsive hosts. To do so, they were attempting to connect to 127.0.0.2 and 127.0.0.3. However, some hosts are configured to respond to 127.0.0.0/8 as localhost, and with such a configuration, these tests could fail.
One alternative is to configure mongodb to bind specifically to 127.0.0.1. Another would be a test helper that tests the expected IP to make sure nothing responds before running the test, possibly skipping it if something responds (or trying another address?) But this solution seems like the simplest, easiest change to make, that covers the most possible configurations.
=> Don't assume that 127.0.0.[2-255] aren't in use.

.github/workflows/main.yml, .travis.yml, alerts/client.go, alerts/client_test.go, alerts/repo.go, auth/client/client.go, auth/client/external.go, auth/service/service/service.go, client/client.go, client/client_test.go, client/config.go, client/config_test.go, data/client/client.go, data/client/client_test.go, data/service/service/standard.go, metric/client/client_test.go, platform/client.go, platform/config.go, platform/config_test.go, prescription/application/application.go, service/service/DEPRECATED_service.go, service/service/authenticated.go, task/service/service/service.go, user/client/client.go
This client was part of [hydrophone-126](https://github.com/tidepool-org/hydrophone/pull/126), but is extracted out to platform. It makes more sense for it to be in platform, where it's service endpoints are defined.
BACK-2500
=> [BACK-2737] adds an alerts client

data/service/api/v1/alerts.go
These are more or less impossible to diagnose without any log info. I'm seeing an issue in a QA environment that I can't reproduce running locally, so the extra information will hopefully give me the insight I need to get over this hump.
BACK-2500
=> rlog internal server errors

blob/client/client.go, client/client.go, client/client_test.go, dexcom/client/client.go, oauth/client/client.go, oauth/client/client_test.go, platform/client_test.go, request/inspector.go, request/inspector_test.go
The oauth.Client.SendOauthRequest method is modified to accept a
[]request.ResponseInspect. One of these inspectors generates prometheus
metrics calls to track Dexcom API usage by number of calls, path, and status
code.
This is done in response to use seeing some 429 (too many requests) errors in our logs. With the visibility these metrics provide, we hope to better understand our usage of the Dexcom API, so that we can take steps to reduce our usage if necessary, or at least have a meaningful discussion with Dexcom about how much we'd like to use their API.
BACK-2820
=> add basic Dexcom API metrics

data/service/api/v1/datasets_data_create.go, data/service/api/v1/datasets_data_create_provenance_test.go
In a previous commit (see BACK-2995), empty tokens were excluded, but there can be tokens that aren't JWTs, which would still trigger a spurious log message. This change removes more cases where a token exists, but isn't a JWT. The goal is to log a warning when we expect a JWT, but don't get one.
BACK-3027
=> don't look for device data provenance without a JWT (part 2)

data/service/api/v1/datasets_data_create.go, data/service/api/v1/datasets_data_create_provenance_test.go
Warnings about missing user id fields were being logged in cases where we don't expect there to be a user id. Namely, when the request is using a server session token.
Waiting for #723 before merging.
=> quiet data provenance logs

data/service/api/v1/users_datasets_create_test.go, data/store/mongo/mongo_datum.go, data/store/mongo/mongo_test.go, data/store/store.go, data/store/test/data_repository.go, tools/benchmark_data_store/benchmark_data_store.go
Where alertable data means those data used when evaluating whether a defined alert configuration is triggered, and a notification needs to be sent.
BACK-2554
=> adds a mongodb query for alertable data

application/provider.go, log/devlog/devlog.go, log/devlog/devlog_suite_test.go, log/devlog/devlog_test.go
JSON logging is great for production, but when running things locally, it's very helpful to have something more readable.
This devlog injects itself when the POD_NAMESPACE env var is "default" (used by the development repo's local k8s cluster) or when the TIDEPOOL_USE_DEVLOG env var is set (to any non-blank value).
It has a few features:
1. shortens timestamp
2. leaves out process information
3. shows basic caller information only for error messages (filename:line)
4. abbreviates log level output ("error" => "EE", "debug" => "DD", etc)
5. handles other fields by appending them to the main log message
=> adds a plain-text logger for development or testing

Makefile
Some travis builds have failed because TIMESTAMP experiences a skew. Since timestamp is only created in the one place, this should fix the issue.
https://www.gnu.org/software/make/manual/html_node/Variables_002fRecursion.html
This will probably wait until after @darinkrauss finishes his cleanup passes?
=> Makefile: export TIMESTAMP to prevent skew

.travis.yml
As far as we can tell, travis has updated some of the packages in their jammy
image. Notably mongodb's version got bumped up (we actually have to downgrade
now), and their version of docker was bumped, which causes us to have to
install the buildx plugin via a different package (seems they have both the
ubuntu apt sources and the docker.com apt sources which somehow used to play
nice until now?)
In addition we were using the mongo 7.x repo despite installing 6.x. I'm not
sure how that ever worked, but they've been put back into sync.
=> update to match changed mongodb version scheme

data/blood/glucose/glucose.go, data/blood/glucose/glucose_test.go, data/blood/glucose/test/glucose.go, data/types/blood/blood.go, data/types/blood/glucose/selfmonitored/selfmonitored.go, data/types/blood/glucose/selfmonitored/selfmonitored_test.go, data/types/blood/test/blood.go
use a generic object to store raw units and value for SMBG. Use the raw details to generate the legacy identity
=> have generic raw object for units and value

Makefile
Under certain conditions (my custom Tilt setup), when Tilt tries to build
platform services, it ignores the .git directory, which causes calculations of
the git SHA checksums to be empty. The data service refuses to start without
some value. This change provides a fallback in the event that no git
information is available.
This shouldn't affect any of our existing build/deployment processes, which
obviously do have git values included, so if you notice anything different,
let me know.
=> add a fallback for Makefile's git SHA checksum calculation

alerts/client.go, data/events/alerts.go, data/events/events.go, data/events/events_test.go, data/service/service/standard.go, vendor/github.com/IBM/sarama/mocks/README.md, vendor/github.com/IBM/sarama/mocks/async_producer.go, vendor/github.com/IBM/sarama/mocks/consumer.go, vendor/github.com/IBM/sarama/mocks/mocks.go, vendor/github.com/IBM/sarama/mocks/sync_producer.go, vendor/modules.txt
When a care partner alert encounters an error, the message is moved to a separate topic that will cause it to be retried after a delay. Any number of these topics can be configured.
=> add a topic shifting retry mechanism for care partner alerts

Makefile
This should add suitable flags to approximate what we currently have with
ginkgo / ci-test.
=> adds go-ci-test Makefile target

.travis.yml, Makefile
This is intended as a trial to ensure that both make ci-test and make go-ci-test find the same errors. The latter is significantly faster, so it would be preferable to use it instead, but of course we need to ensure that we're not running things incorrectly or missing out on something provided by the current ginkgo-based solution.
For more info/discussion:
- https://tidepoolteam.slack.com/archives/CF59ADWLB/p1727967169327199
- https://github.com/tidepool-org/platform/pull/777
=> run both ci-test and go-ci-test via Travis.

Makefile
- Conditionally add `-private` suffix to repository name by passing `$PRIVATE=true` environment variable
- Allow specifying a subset of services to be built (we'll only need to build `data` and `auth` services in the private repository
=> Makefile changes to support private repository builds

request/mutator_test.go, request/parser_test.go
A few of these tests assumed that their generated keys were unique, when they weren't, which lead to flappy tests.
I'm not sure I've found them all, but I was able to run them with --repeat 20000 without a failure.
=> fixes a few flappy tests

.travis.yml, Makefile
Running ci tests via ginkgo is slower, and our tests[1] indicate that the results are identical, so just run the faster one.
[1]: https://tidepoolteam.slack.com/archives/CF59ADWLB/p1732571354736099
=> run only go-ci-test for CI testing needs

Makefile
This is to parallel the CI server, which is using go-ci-test.
The old test target is now ginkgo-test.
=> rearrange the test target to point to go-test

data/store/mongo/mongo_datum.go, data/store/mongo/mongo_test.go
There are additional optimizations that can be made (~5% gains but that will require a rebuild of some of the indexes so that can be deferred until later).
This is a cleaned up verison of `jimmy-back-2416-shadowing-service-prefix` as that had experiimental indexes, and therefor experimental names that I cant just cherry pick onto here, as we can't rename an index in MDB.
This PR also removes the disable user events handler and direct connection to shoreline to keep things cleaner.
=> [BACK-3097] Final index and changes from sharded cluster in prep for sharding.

Makefile
egrep is deprecated now, at least on my Linux box, so this was
spitting out tons of warning messages, which this change stops.
=> change egrep to grep -E

ehr/sync/task.go, ehr/sync/task_test.go
EHR sync tasks fail if they don't have an explicitly set cadence because of a panic due to a nil pointer dereferencing. The intention in the original implementation was to use the default 14 days.
=> [BACK-3442] Prevent panics if ehr sync tasks don't have a cadence set

data/blood/glucose/glucose.go, data/blood/glucose/glucose_test.go, data/blood/glucose/test/target.go, data/types/blood/glucose/continuous/continuous.go, data/types/blood/glucose/continuous/continuous_test.go, data/types/settings/cgm/rate_alert.go, data/types/settings/cgm/rate_alert_test.go, data/types/settings/cgm/test/rate_alert.go, dexcom/fetch/translate.go
- Add trend rate units to cbg data type
- Update general blood glucose functionality
- Use trend rate in Dexcom data
- https://tidepool.atlassian.net/browse/BACK-3461
=> [BACK-3461] Add trend rate units to cbg data type

data/service/api/v1/partners.go, data/service/api/v1/v1.go
Note: This implementation is a temporary placeholder to allow bootstrapping of the Abbott OAuth client workflow. Will need to migrate this to environment variables and add minimal authorization. For now, though, this is acceptable since it isn't revealing anything that is not already available in other locations (i.e. other public repos).
TODO: https://tidepool.atlassian.net/browse/BACK-3394
=> [BACK-3392] Add OpenID sector for Abbott OAuth

data/types/blood/glucose/continuous/continuous.go, data/types/blood/glucose/continuous/continuous_test.go
DIY Loop doesn't send trend rate units which prevents CBG data from being uploaded due to too stringent validation. We could potentially try to infer trend rate units from the blood glucose units, but that doesn't seem ideal.
=> Make trend rate units optional

data/types/bolus/bolus.go, data/types/bolus/bolus_test.go, data/types/device/override/settings/pump/pump.go, data/types/device/override/settings/pump/pump_test.go, data/types/settings/pump/override_preset.go, data/types/settings/pump/override_preset_test.go
- Use milliseconds for duration in pumpSettingsOverride
- Use milliseconds for duration in pumpSettings.overridePresets
- Add deliveryContext property to all bolus types
- Remove pumpSettingsOverride validation of required properties
- https://tidepool.atlassian.net/browse/BACK-2773
- https://tidepool.atlassian.net/browse/BACK-3474
- https://tidepool.atlassian.net/browse/BACK-3475
=> [BACK-2773/3474/3475] Updates to data model for twiist integration

.travis.yml, Makefile, migrations/start.sh, services/auth/start.sh, services/blob/start.sh, services/data/start.sh, services/prescription/start.sh, services/task/start.sh, tools/start.sh
- Remove unnecessary deploy targets in Makefile
- Remove unnecessary gopath-implode target in Makefile
- Update .travis.yml
- https://tidepool.atlassian.net/browse/BACK-3720
=> [BACK-3720] Remove unnecessary deploy targets in Makefile

data/deduplicator/deduplicator.go, data/deduplicator/deduplicator/base.go, data/deduplicator/deduplicator/base_test.go, data/deduplicator/deduplicator/data_set_delete_origin.go, data/deduplicator/deduplicator/data_set_delete_origin_base.go, data/deduplicator/deduplicator/data_set_delete_origin_older.go, data/deduplicator/deduplicator/data_set_delete_origin_older_test.go, data/deduplicator/deduplicator/data_set_delete_origin_test.go, data/deduplicator/deduplicator/device_deactivate_hash.go, data/deduplicator/deduplicator/device_deactivate_hash_test.go, data/deduplicator/deduplicator/device_truncate_data_set.go, data/deduplicator/deduplicator/device_truncate_data_set_test.go, data/deduplicator/deduplicator/none.go, data/deduplicator/deduplicator/none_test.go, data/deduplicator/factory/factory.go, data/deduplicator/factory/factory_test.go, data/deduplicator/test/deduplicator.go, data/service/api/v1/datasets_data_create.go, data/service/api/v1/datasets_data_delete.go, data/service/api/v1/datasets_delete.go, data/service/api/v1/datasets_update.go, data/service/api/v1/users_datasets_create.go, data/service/service/standard.go
- Refactor data deduplicator dependencies
- Inject repository into data deduplicator during creation
- Remove repository from various data deduplicator functions
- Remove unnecessary data set validation in data deduplicator factory
- Reorder data service initialization to allow data deduplicator dependencies
- https://tidepool.atlassian.net/browse/BACK-3723
=> [BACK-3723] Refactor data deduplicator dependencies

auth/client/client.go, auth/events/events.go, auth/provider_session.go, auth/service/api/v1/auth_service_mock.go, auth/service/api/v1/provider_session.go, auth/service/client.go, auth/service/service.go, auth/service/service/client.go, auth/service/service/service.go, auth/service/test/service.go, auth/store/mongo/provider_session_repository.go, auth/store/store.go, auth/store/test/provider_session_repository.go, auth/test/mock.go, auth/test/provider_session_accessor.go, page/pagination.go, page/pagination_test.go, page/test/pagination.go
- Refactor provider session API and repository functions
- Rename DeleteAllProviderSessions to DeleteUserProviderSessions
- Move ListAllProviderSessions to repository only
- Add page.Paginator to enable easier paging through results
- https://tidepool.atlassian.net/browse/BACK-3724
=> [BACK-3724] Refactor provider session API and repository functions

twiist/provider/provider.go
- Temporarily restore twiist use of TidepoolLinkId
- https://tidepool.atlassian.net/browse/BACK-3921
=> [BACK-3921] Temporarily restore twiist use of TidepoolLinkId
